---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, bluexp, cloud volumes ontap, licenses, digital wallet, subscriptions, cloud backup, cloud tiering, data sense, ransomware, connector, amazon fsx for ontap, azure netapp files, cloud sync, e-series, global file cache, google cloud, disaster recovery, backup and recovery, classification, copy and sync, edge cache, edge caching, volume caching, ontap clusters, alerts, identity and access management, iam, recovery, netapp console, console' 
summary: Obtenga información sobre los cambios más recientes en las características y los servicios de datos que forman parte de la consola de NetApp . 
---
= Cambios recientes en la consola de NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Obtenga información sobre los cambios más recientes en las características y los servicios de datos que forman parte de la consola de NetApp .  Para obtener un historial de lanzamiento completo, vaya alink:release-notes-index.html["conjunto completo de notas de la versión"] para cada servicio individual.



== Funciones administrativas

En esta sección se describen las nuevas funciones relacionadas con las funciones de administración de la consola de NetApp : organizaciones, identificación y acceso, agentes de la consola, credenciales del proveedor de nube y más.

Directiva sin resolver en <stdin> - incluye: https://raw.githubusercontent.com/NetAppDocs/console-setup-admin/main/whats-new.adoc [tag=whats-new,leveloffset=+1]



== Alertas



=== 6 de octubre de 2025



==== Las BlueXP alerts ahora son alertas de ONTAP

Las BlueXP alerts han cambiado de nombre a alertas de ONTAP .

Puede acceder a él desde la barra de navegación izquierda de la consola de NetApp seleccionando *Almacenamiento* > *Alertas*.



==== BlueXP ahora es NetApp Console

La consola NetApp , construida sobre la base BlueXP mejorada y reestructurada, proporciona una gestión centralizada del almacenamiento NetApp y de los servicios de datos NetApp en entornos locales y en la nube a nivel empresarial, brindando información en tiempo real, flujos de trabajo más rápidos y una administración simplificada, que es altamente segura y compatible.

Para obtener más detalles sobre lo que ha cambiado, consulte lalink:https://docs.netapp.com/us-en/bluexp-relnotes/index.html["Notas de la versión de la consola de NetApp"] .



=== 7 de octubre de 2024



==== Página de lista de BlueXP alerts

Puede identificar rápidamente los clústeres de ONTAP que tienen baja capacidad o bajo rendimiento, evaluar el grado de disponibilidad e identificar riesgos de seguridad. Puede ver alertas relacionadas con la capacidad, el rendimiento, la protección, la disponibilidad, la seguridad y la configuración.



==== Detalles de las alertas

Puede explorar los detalles de las alertas y encontrar recomendaciones.



==== Ver detalles del clúster vinculados a ONTAP System Manager

Con las BlueXP alerts, puede ver las alertas asociadas con su entorno de almacenamiento de ONTAP y profundizar en los detalles vinculados a ONTAP System Manager.

https://docs.netapp.com/us-en/bluexp-alerts/concept-alerts.html["Obtenga más información sobre las BlueXP alerts"] .



== Amazon FSx para ONTAP

Directiva sin resolver en <stdin> - incluye: https://raw.githubusercontent.com/NetAppDocs/console-fsx-ontap/main/whats-new.adoc [tag=whats-new,leveloffset=+1]



== Almacenamiento de Amazon S3

Directiva sin resolver en <stdin> - incluye: https://raw.githubusercontent.com/NetAppDocs/storage-managment-s3-storage/main/whats-new.adoc [tag=whats-new,leveloffset=+1]



== Almacenamiento de blobs de Azure

Directiva sin resolver en <stdin> - incluye: https://raw.githubusercontent.com/NetAppDocs/storage-management-blob-storage/main/whats-new.adoc [tag=whats-new,leveloffset=+1]



== Azure NetApp Files

Directiva sin resolver en <stdin> - incluye: https://raw.githubusercontent.com/NetAppDocs/storage-management-azure-netapp-files/main/whats-new.adoc [tag=whats-new,leveloffset=+1]



== Copia de seguridad y recuperación

Directiva sin resolver en <stdin> - incluye: https://raw.githubusercontent.com/NetAppDocs/data-services-backup-recovery/main/whats-new.adoc [tag=whats-new,leveloffset=+1]



== Clasificación de datos

Directiva sin resolver en <stdin> - incluye: https://raw.githubusercontent.com/NetAppDocs/data-services-data-classification/main/whats-new.adoc [tag=whats-new,leveloffset=+1]



== Cloud Volumes ONTAP

Directiva sin resolver en <stdin> - incluye: https://raw.githubusercontent.com/NetAppDocs/storage-management-cloud-volumes-ontap/main/whats-new.adoc [tag=whats-new,leveloffset=+1]



== Copiar y sincronizar

Directiva sin resolver en <stdin> - incluye: https://raw.githubusercontent.com/NetAppDocs/data-services-copy-sync/main/whats-new.adoc [tag=whats-new,leveloffset=+1]



== Asesor digital



=== 6 de octubre de 2025



==== BlueXP ahora es NetApp Console

La consola NetApp , construida sobre la base BlueXP mejorada y reestructurada, proporciona una gestión centralizada del almacenamiento NetApp y de los servicios de datos NetApp en entornos locales y en la nube a nivel empresarial, brindando información en tiempo real, flujos de trabajo más rápidos y una administración simplificada, que es altamente segura y compatible.

Para obtener más detalles sobre lo que ha cambiado, consulte la https://docs.netapp.com/us-en/bluexp-relnotes/index.html["Notas de la versión de la consola de NetApp"] .



=== 6 de agosto de 2025



==== Soporte para conmutadores con derechos

Ahora puede ver información sobre los conmutadores SAN Fibre Channel de Brocade que tienen derecho a recibir soporte. Esto incluye detalles sobre el modelo del conmutador, el número de serie y el estado de soporte. link:https://docs.netapp.com/us-en/active-iq/task_view_inventory_details.html["Aprenda a ver los interruptores con derecho de soporte"] .



==== Umbral para los datos de RSS AutoSupport

El límite de envíos recientemente detenidos (RSS), en el widget AutoSupport , se ha ampliado de 48 horas (2 días) a 216 horas (9 días) antes de que un sistema sea marcado como RSS. Esto se hace para dar cabida a plataformas como StorageGRID que solo envían datos de AutoSupport semanales.



==== Sección de API obsoleta en el catálogo de API de Digital Advisor

Una nueva sección de API obsoleta está disponible en el catálogo de API de Digital Advisor . Se enumeran las API que están programadas para quedar obsoletas, junto con los cronogramas de obsolescencia y las API alternativas.



==== Pronóstico de capacidad V2 y obsolescencia de los módulos API de fin de soporte

Se prevé que los módulos API de pronóstico de capacidad V2 y fin de soporte queden obsoletos. Para acceder a las API obsoletas o conocer los plazos de desuso y las API alternativas, navegue a *Servicios de API -> Explorar -> API obsoletas*.



=== 9 de julio de 2025



==== Asesor de actualizaciones

* Se ha incluido una opción de descarga multiformato para los planes de Upgrade Advisor para simplificar la planificación de la actualización de ONTAP y abordar posibles bloqueadores o advertencias.  Ahora puede descargar los planes del asesor de actualizaciones en formatos Excel, PDF y JSON.
* En el formato Excel del plan Upgrade Advisor, se han realizado las siguientes mejoras:
+
** Puede ver las comprobaciones previas realizadas en el clúster y marcar los resultados con indicadores como "Aprobado", "Reprobado" o "Omitido".  Esto garantiza que el clúster esté en condiciones óptimas para completar la actualización de ONTAP .
** Puede ver las últimas actualizaciones de firmware recomendadas aplicables al clúster, junto con la versión enviada con la versión de destino de ONTAP .
** Se ha incluido una nueva pestaña que ofrece comprobaciones de interoperabilidad para clústeres SAN.  Proporciona una vista de las versiones del sistema operativo host compatibles con la versión de ONTAP de destino seleccionada.






== Licencias y suscripciones



=== 6 de octubre de 2025



==== BlueXP ahora es NetApp Console

La consola NetApp , construida sobre la base BlueXP mejorada y reestructurada, proporciona una gestión centralizada del almacenamiento NetApp y de los servicios de datos NetApp en entornos locales y en la nube a nivel empresarial, brindando información en tiempo real, flujos de trabajo más rápidos y una administración simplificada, que es altamente segura y compatible.

Para obtener más detalles sobre lo que ha cambiado, consulte lalink:https://docs.netapp.com/us-en/bluexp-relnotes/index.html["Notas de la versión de la consola de NetApp"] .



=== 10 de marzo de 2025



==== Capacidad de eliminar suscripciones

Ahora puedes eliminar suscripciones de la billetera digital si te has dado de baja de ellas.



==== Ver la capacidad consumida para las suscripciones de Marketplace

Al ver las suscripciones PAYGO, ahora puedes ver la capacidad consumida de la suscripción.



=== 10 de febrero de 2025

La BlueXP digital wallet ha sido rediseñada para facilitar su uso y ahora ofrece gestión adicional de suscripciones y licencias.



==== Nuevo panel de descripción general

La página de inicio de la billetera digital tiene un panel actualizado de sus licencias de NetApp y suscripciones de Marketplace, con la capacidad de desglosar servicios específicos, tipos de licencias y acciones requeridas.



==== Configuración de suscripciones a credenciales

La BlueXP digital wallet ahora te permite configurar tus suscripciones con credenciales de proveedor. Normalmente esto se hace cuando se suscribe por primera vez a una suscripción de Marketplace o a un contrato anual. Anteriormente, cambiar las credenciales de la suscripción solo se podía hacer en la página Credenciales.



==== Asociar suscripciones con organizaciones

Ahora puedes actualizar la organización a la que está asociada una suscripción directamente desde la billetera digital.



==== Administración de licencias de Cloud Volume ONTAP

Ahora puede administrar las licencias de Cloud Volumes ONTAP a través de la página de inicio o la pestaña *Licencias directas*. Utilice la pestaña *Suscripciones del Marketplace* para ver la información de su suscripción.



=== 5 de marzo de 2024



==== BlueXP disaster recovery

La BlueXP digital wallet ahora le permite administrar licencias para la BlueXP disaster recovery. Puede agregar licencias, actualizar licencias y ver detalles sobre la capacidad autorizada.

https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-data-services-licenses.html["Aprenda a administrar licencias para los servicios de datos de BlueXP"]



=== 30 de julio de 2023



==== Mejoras en los informes de uso

Ahora están disponibles varias mejoras en los informes de uso de Cloud Volumes ONTAP :

* La unidad TiB ahora está incluida en el nombre de las columnas.
* Ahora se incluye un nuevo campo _node(s)_ para números de serie.
* Ahora se incluye una nueva columna _Tipo de carga de trabajo_ en el informe de uso de máquinas virtuales de almacenamiento.
* Los nombres de los entornos de trabajo ahora se incluyen en los informes de uso de volúmenes y máquinas virtuales de almacenamiento.
* El tipo de volumen _archivo_ ahora está etiquetado como _Principal (Lectura/Escritura)_.
* El tipo de volumen _secundario_ ahora está etiquetado como _Secundario (DP)_.


Para obtener más información sobre los informes de uso, consulte https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-capacity-licenses.html#download-usage-reports["Descargar informes de uso"] .



== Recuperación ante desastres

Directiva sin resolver en <stdin> - incluye: https://raw.githubusercontent.com/NetAppDocs/storage-management-disaster-recovery/main/release-notes/dr-whats-new.adoc [tag=whats-new,leveloffset=+1]



== Sistemas de la serie E

Directiva sin resolver en <stdin> - incluye: https://raw.githubusercontent.com/NetAppDocs/storage-management-e-series/main/whats-new.adoc [tag=whats-new,leveloffset=+1]



== Planificación del ciclo de vida



=== 6 de octubre de 2025



==== La BlueXP economic efficiency ahora es la planificación del ciclo de vida

La BlueXP economic efficiency ha pasado a llamarse Planificación del ciclo de vida.

Puede acceder a él desde la barra de navegación izquierda de la consola de NetApp seleccionando *Almacenamiento* > *Planificación del ciclo de vida*.



==== BlueXP ahora es NetApp Console

La consola NetApp , construida sobre la base BlueXP mejorada y reestructurada, proporciona una gestión centralizada del almacenamiento NetApp y de los servicios de datos NetApp en entornos locales y en la nube a nivel empresarial, brindando información en tiempo real, flujos de trabajo más rápidos y una administración simplificada, que es altamente segura y compatible.

Para obtener más detalles sobre lo que ha cambiado, consulte lalink:https://docs.netapp.com/us-en/bluexp-relnotes/index.html["Notas de la versión de la consola de NetApp"] .



=== 15 de mayo de 2024



==== Funciones deshabilitadas

Algunas funciones de BlueXP economic efficiency se han desactivado temporalmente:

* Actualización tecnológica
* Añadir capacidad




=== 14 de marzo de 2024



==== Opciones de actualización tecnológica

Si tiene activos existentes y desea determinar si es necesario actualizar una tecnología, puede utilizar las opciones de actualización de tecnología de eficiencia económica de BlueXP . Puede revisar una evaluación breve de sus cargas de trabajo actuales y obtener recomendaciones o, si envió registros de AutoSupport a NetApp en los últimos 90 días, el servicio ahora puede proporcionar una simulación de carga de trabajo para ver cómo funcionan sus cargas de trabajo en hardware nuevo.

También puede agregar una carga de trabajo y excluir cargas de trabajo existentes de la simulación.

Anteriormente, solo era posible realizar una evaluación de sus activos e identificar si era recomendable actualizar su tecnología.

La función ahora es parte de la opción Actualización de tecnología en la navegación izquierda.

Obtenga más información sobre el https://docs.netapp.com/us-en/bluexp-economic-efficiency/use/tech-refresh.html["Evaluar una actualización tecnológica"] .



== Almacenamiento en caché perimetral

El servicio de almacenamiento en caché de borde se eliminó el 7 de agosto de 2024.



== Google Cloud NetApp Volumes

Directiva sin resolver en <stdin> - incluye: https://raw.githubusercontent.com/NetAppDocs/storage-management-google-cloud-netapp-volumes/main/whats-new.adoc [tag=whats-new,leveloffset=+1]



== Almacenamiento en la nube de Google

Directiva sin resolver en <stdin> - incluye: https://raw.githubusercontent.com/NetAppDocs/storage-management-google-cloud-storage/main/whats-new.adoc [tag=whats-new,leveloffset=+1]



== Keystone



=== 6 de octubre de 2025



==== BlueXP ahora es NetApp Console

La consola NetApp , construida sobre la base BlueXP mejorada y reestructurada, proporciona una gestión centralizada del almacenamiento NetApp y de los servicios de datos NetApp en entornos locales y en la nube a nivel empresarial, brindando información en tiempo real, flujos de trabajo más rápidos y una administración simplificada, que es altamente segura y compatible.

2ef72cc8a56fc5999e258b450b9fca24



=== 22 de septiembre de 2025



==== Adición de monitoreo de alertas

El panel de Keystone en BlueXP ahora incluye una pestaña *Monitoreo* para administrar alertas y monitores en todas sus suscripciones. Esta nueva pestaña le permite:

* Ver y resolver alertas activas, incluidas las alertas generadas por el sistema y definidas por el usuario sobre el uso de la capacidad y el vencimiento de la suscripción.
* Cree monitores de alerta para rastrear el uso de la capacidad y los eventos de vencimiento de suscripciones.


Para obtener más información, consultelink:https://docs.netapp.com/us-en/keystone-staas/integrations/monitoring-alerts.html["Ver y administrar alertas y monitores"] .



==== Visualización optimizada de los niveles de servicio de rendimiento

Puede ver la información de los niveles de rendimiento del servicio, ahora movida de una pestaña separada a una vista expandible, dentro de la pestaña *Suscripciones*. Haga clic en la flecha hacia abajo junto a la columna *Fecha de vencimiento* para verlas para cada suscripción. Para obtener más información, consultelink:https://docs.netapp.com/us-en/keystone-staas/integrations/subscriptions-tab.html["Ver detalles sobre sus suscripciones a Keystone"] .



=== 28 de agosto de 2025



==== Seguimiento de uso lógico mejorado con una nueva columna

Se agrega una nueva columna, Huella total, para mejorar el seguimiento del consumo de Keystone para los volúmenes de FabricPool :

* * Panel de control de Keystone en BlueXP*: puede ver la columna *Huella total* en la pestaña *Volúmenes en clústeres* dentro de la pestaña *Activos*.
* * Digital Advisor*: Puede ver la columna * Huella total * en la pestaña * Detalles de volumen * dentro de la pestaña * Volúmenes y objetos *.


Esta columna muestra la huella lógica total de los volúmenes que utilizan niveles de FabricPool , incluidos datos de los niveles de rendimiento y de los niveles fríos, para que pueda calcular con precisión el consumo de Keystone .



== Kubernetes

El soporte para descubrir y administrar clústeres de Kubernetes se eliminó el 7 de agosto de 2024.



== Informes de migración

El servicio de informes de migración se eliminó el 7 de agosto de 2024.



== Clústeres ONTAP locales

Directiva sin resolver en <stdin> - incluye: https://raw.githubusercontent.com/NetAppDocs/storage-management-ontap-onprem/main/whats-new.adoc [tag=whats-new,leveloffset=+1]



== Resiliencia operativa

Las funciones de resiliencia operativa se eliminaron el 22 de agosto de 2025.



== Resiliencia frente al ransomware

Directiva sin resolver en <stdin> - incluye: https://raw.githubusercontent.com/NetAppDocs/data-services-ransomware-resilience/main/whats-new.adoc [tag=whats-new,leveloffset=+1]



== Remediación

El servicio de remediación se eliminó el 22 de abril de 2024.



== Replicación

Directiva sin resolver en <stdin> - incluye: https://raw.githubusercontent.com/NetAppDocs/data-services-replication/main/whats-new.adoc [tag=whats-new,leveloffset=+1]



== Actualizaciones de software

Directiva sin resolver en <stdin> - incluye: https://raw.githubusercontent.com/NetAppDocs/console-software-updates/main/release-notes/whats-new.adoc [tag=whats-new,leveloffset=+1]



== StorageGRID

Directiva sin resolver en <stdin> - incluye: https://raw.githubusercontent.com/NetAppDocs/storage-managment-storagegrid/main/whats-new.adoc [tag=whats-new,leveloffset=+1]



== Nivelación de la nube

Directiva sin resolver en <stdin> - incluye: https://raw.githubusercontent.com/NetAppDocs/data-service-cloud-tiering/main/whats-new.adoc [tag=whats-new,leveloffset=+1]



== Almacenamiento en caché de volumen

Directiva sin resolver en <stdin> - incluye: https://raw.githubusercontent.com/NetAppDocs/console-volume-caching/main/release-notes/cache-whats-new.adoc [tag=whats-new,leveloffset=+1]



== Fábrica de carga de trabajo



=== 29 de junio de 2025



==== Actualización de permisos para bases de datos

El siguiente permiso ahora está disponible en modo de solo lectura para bases de datos: `cloudwatch:GetMetricData` .

https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["Registro de cambios de referencia de permisos"]



==== Compatibilidad con el servicio de notificación de BlueXP workload factory

El servicio de notificación de la BlueXP workload factory permite que la fábrica de carga de trabajo envíe notificaciones al servicio de BlueXP alerts o a un tema de Amazon SNS.  Las notificaciones enviadas a las BlueXP alerts aparecen en el panel de BlueXP alerts .  Cuando la fábrica de carga de trabajo publica notificaciones en un tema de Amazon SNS, los suscriptores del tema (como personas u otras aplicaciones) reciben las notificaciones en los puntos finales configurados para el tema (como mensajes de correo electrónico o SMS).

https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["Configurar las notificaciones de BlueXP workload factory"]



=== 4 de mayo de 2025



==== Compatibilidad con autocompletado de CloudShell

Al utilizar la BlueXP workload factory CloudShell, puede comenzar a escribir un comando y presionar la tecla Tab para ver las opciones disponibles.  Si existen múltiples posibilidades, la CLI mostrará una lista de sugerencias.  Esta función mejora la productividad al minimizar los errores y acelerar la ejecución de comandos.



==== Terminología de permisos actualizada

La interfaz de usuario y la documentación de la fábrica de carga de trabajo ahora usan "solo lectura" para referirse a los permisos de lectura y "lectura/escritura" para referirse a los permisos de automatización.



=== 30 de marzo de 2025



==== CloudShell informa respuestas de error generadas por IA para los comandos CLI de ONTAP

Al usar CloudShell, cada vez que emite un comando CLI de ONTAP y se produce un error, puede obtener respuestas de error generadas por IA que incluyen una descripción de la falla, la causa de la falla y una resolución detallada.

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html["Utilice CloudShell"]



==== iam:SimulatePermissionPolicy actualización de permisos

Ahora puedes administrar el `iam:SimulatePrincipalPolicy` permiso de la consola de fábrica de carga de trabajo cuando agrega credenciales de cuenta de AWS adicionales o agrega una nueva capacidad de carga de trabajo, como la carga de trabajo GenAI.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["Registro de cambios de referencia de permisos"]



=== 02 de febrero de 2025



==== CloudShell disponible en la consola de BlueXP workload factory

CloudShell está disponible desde cualquier lugar en la consola de BlueXP workload factory .  CloudShell le permite usar las credenciales de AWS y ONTAP que proporcionó en su cuenta de BlueXP y ejecutar comandos de AWS CLI o comandos de ONTAP CLI en un entorno similar a un shell.

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html["Utilice CloudShell"]



==== Actualización de permisos para bases de datos

El siguiente permiso ahora está disponible en modo _lectura_ para bases de datos: `iam:SimulatePrincipalPolicy` .

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["Registro de cambios de referencia de permisos"]
