---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, bluexp, cloud volumes ontap, licenses, digital wallet, subscriptions, cloud backup, cloud tiering, data sense, ransomware, connector, agent, amazon fsx for ontap, azure netapp files, cloud sync, e-series, google cloud, disaster recovery, backup and recovery, classification, copy and sync, edge cache, edge caching, volume caching, ontap clusters, alerts, identity and access management, iam, recovery, netapp console, console' 
summary: Obtenga información sobre los cambios más recientes en las características y los servicios de datos que forman parte de la NetApp Console. 
---
= Cambios recientes en la NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Obtenga información sobre los cambios más recientes en las características y los servicios de datos que forman parte de la NetApp Console.  Para obtener un historial de lanzamiento completo, vaya alink:release-notes-index.html["conjunto completo de notas de la versión"] para cada servicio individual.



== Servicios obsoletos



=== Almacenamiento en caché perimetral

El servicio de almacenamiento en caché de borde se eliminó el 7 de agosto de 2024.



=== Kubernetes

El soporte para descubrir y administrar clústeres de Kubernetes se eliminó el 7 de agosto de 2024.



=== Informes de migración

El servicio de informes de migración se eliminó el 7 de agosto de 2024.



=== Resiliencia operativa

Las funciones de resiliencia operativa se eliminaron el 22 de agosto de 2025.



=== Remediación

El servicio de remediación se eliminó el 22 de abril de 2024.
