---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, bluexp, cloud volumes ontap, licenses, digital wallet, subscriptions, cloud backup, cloud tiering, data sense, ransomware, connector, agent, amazon fsx for ontap, azure netapp files, cloud sync, e-series, google cloud, disaster recovery, backup and recovery, classification, copy and sync, edge cache, edge caching, volume caching, ontap clusters, alerts, identity and access management, iam, recovery, netapp console, console' 
summary: Obtenga información sobre los cambios más recientes en las características y los servicios de datos que forman parte de la NetApp Console. 
---
= Cambios recientes en la NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Obtenga información sobre los cambios más recientes en las características y los servicios de datos que forman parte de la NetApp Console.  Para obtener un historial de lanzamiento completo, vaya alink:release-notes-index.html["conjunto completo de notas de la versión"] para cada servicio individual.



== Servicios obsoletos



=== Almacenamiento en caché perimetral

El servicio de almacenamiento en caché de borde se eliminó el 7 de agosto de 2024.



=== Kubernetes

El soporte para descubrir y administrar clústeres de Kubernetes se eliminó el 7 de agosto de 2024.



=== Informes de migración

El servicio de informes de migración se eliminó el 7 de agosto de 2024.



=== Resiliencia operativa

Las funciones de resiliencia operativa se eliminaron el 22 de agosto de 2025.



=== Remediación

El servicio de remediación se eliminó el 22 de abril de 2024.



== 14 de enero de 2026



=== Clasificación de datos



==== Versión 1.50

Esta versión de Clasificación de datos incluye correcciones de errores y las siguientes actualizaciones:

.Mejoras en la clasificación personalizada
La clasificación de datos ahora admite la creación de categorías personalizadas para sus datos. Puede cargar archivos para ajustar un modelo de IA que la clasificación de datos utiliza para aplicar el marcador de categoría a los datos. Se ha mejorado la interfaz para todas las clasificaciones personalizadas.

Para obtener más información, consulte link:https://docs.netapp.com/us-en/data-services-data-classification/task-custom-classification.html["Crear una clasificación personalizada"^].

.Definición personalizada de datos obsoletos
La clasificación de datos ahora le permite personalizar la definición de datos obsoletos para que se adapte a las necesidades de su organización. Anteriormente, los datos obsoletos se definían como cualquier dato que se hubiera modificado por última vez hacía tres años. Ahora, los datos obsoletos pueden identificarse según cuándo se accedió a ellos por última vez o cuándo se modificaron por última vez; el período de tiempo puede variar desde hace 6 meses hasta hace 10 años.

Para obtener más información, consulte link:https://docs.netapp.com/us-en/data-services-data-classification/task-stale-data.html["Personalizar la definición de datos obsoletos"^].

.Mejor rendimiento
Se han acortado los tiempos de carga de todas las páginas de Clasificación de datos, el informe de mapeo de datos y los filtros en la página de Investigación.

.Tiempo estimado para los informes de investigación
Cuando descarga un informe de investigación, la Clasificación de datos ahora muestra el tiempo estimado para completar la descarga.



== 12 de enero de 2026



=== Configuración y administración de la consola



==== Agente de consola 4.3.0

La versión 4.3.0 admite tanto el modo estándar como el modo restringido.

Esta versión del agente de consola incluye mejoras de seguridad, correcciones de errores y las siguientes características:

.Capacidad para validar las conexiones de red de los agentes de la consola
Ahora puede validar las conexiones de red de los agentes de consola conectados directamente desde la NetApp Console. Esta función ayuda a verificar la conectividad y solucionar problemas con los agentes de la consola.

link:https://docs.netapp.com/us-en/console-setup-admin/task-troubleshoot-agent.html#verify-network-access["Aprenda a ejecutar comprobaciones de configuración en agentes de la consola."]



==== Administración de la NetApp Console

Esta versión incluye lo siguiente:

.Compatibilidad con la federación cuando la NetApp Console está en modo restringido
Ahora puede habilitar la federación para una organización de NetApp Console que esté en modo restringido. Esto permite a los usuarios iniciar sesión en la consola utilizando sus credenciales corporativas mientras mantienen los beneficios de seguridad del modo restringido.

.Modo de solo lectura
Puede configurar una organización de la NetApp Console en modo de solo lectura. En el modo de solo lectura, los usuarios pueden ver recursos y configuraciones, pero no pueden realizar cambios. Un administrador de organización o un superadministrador puede habilitar el modo de solo lectura para una organización. Cuando el modo de solo lectura está habilitado, los usuarios con roles administrativos deben elevar manualmente sus permisos para realizar cambios según sea necesario.

link:https://docs.netapp.com/us-en/console-setup-admin/task-enable-read-only-mode.html["Aprenda cómo habilitar el modo de solo lectura para una organización de consola."]

link:https://docs.netapp.com/us-en/console-setup-admin/task-user-settings["Aprenda cómo elevar su rol cuando su organización está en modo de solo lectura."]



=== Recuperación ante desastres



==== Compatibilidad con múltiples agentes de consola en entornos locales

Si utiliza recuperación ante desastres en sus instalaciones, ahora puede implementar un agente de consola para cada instancia de vCenter, lo que mejora la resiliencia.

Por ejemplo, si tiene dos sitios (sitios A y B), el sitio A puede tener el agente de consola A conectado a vCenter 1, la implementación de ONTAP 1 y la implementación de ONTAP 2. El sitio B puede tener el agente de consola B conectado a vCenter 2 y a las implementaciones de ONTAP 3 y 4.

Para obtener información sobre el agente de consola en recuperación ante desastres, consulte link:https://docs.netapp.com/us-en/data-services-disaster-recovery/get-started/dr-prerequisites.html#netapp-console-prerequisites["Crear el agente de consola"^].



==== Agregar máquinas virtuales después de la conmutación por error para los planes de replicación mediante protección basada en almacén de datos

Cuando se activa la conmutación por error, cualquier plan de replicación que utilice protección basada en almacén de datos incluye las máquinas virtuales que se hayan agregado al almacén de datos, siempre que se hayan descubierto. Debe proporcionar detalles de mapeo para las máquinas virtuales agregadas antes de que se complete la conmutación por error.

Para obtener más información, consulte link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/failover.html["Aplicaciones de conmutación por error"^].



==== Nuevas notificaciones por correo electrónico

La recuperación ante desastres ahora proporciona notificaciones por correo electrónico para los siguientes eventos:

* Acercándose al límite de uso de la capacidad
* Generación de informe completada
* Fracasos laborales
* Caducidad o infracciones de licencia




==== Mejoras de Swagger

Ahora puede acceder a la documentación de Swagger desde Disaster Recovery. En Recuperación ante desastres, seleccione **Configuración** y luego **Documentación de API** para vincularse a Swagger, o visite esta URL en el modo incógnito/privado de su navegador: link:https://snapcenter.cloudmanager.cloud.netapp.com/api/api-doc/draas["https://snapcenter.cloudmanager.cloud.netapp.com/api/api-doc/draas"^].



==== Interfaces de usuario mejoradas

La recuperación ante desastres ahora proporciona advertencias mejoradas y resoluciones de errores. Esta versión corrige un error que impedía que los trabajos cancelados se mostraran en la interfaz de usuario. Los trabajos cancelados ahora son visibles. También hay una nueva advertencia cuando la misma red de destino se asigna a varias redes de origen diferentes.



==== Conservar la estructura de carpetas de la máquina virtual agregada como predeterminada en los planes de replicación

Cuando se crea una replicación, el nuevo valor predeterminado es conservar la estructura de la carpeta de la máquina virtual. Si el destino de recuperación no tiene la jerarquía de carpetas original, Disaster Recovery la crea. Puede anular la selección de esta opción para ignorar la jerarquía de carpetas original.

Para obtener más información, consulte link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/drplan-create.html["Crear un plan de replicación"^].



=== Resiliencia frente al ransomware



==== Replicar instantáneas en ONTAP

Ransomware Resilience ahora admite agregar la replicación de instantáneas a un sitio ONTAP secundario. Puede crear una estrategia de protección contra ransomware que incluya replicación o utilizar la estrategia predefinida.

Para obtener más información, consulte link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-use-protect.html["Proteja las cargas de trabajo en Ransomware Resilience"^].



==== Excluir cargas de trabajo de Ransomware Resilience

Ransomware Resilience ahora permite excluir cargas de trabajo específicas de un sistema de la protección y del panel de Ransomware Resilience. Puede excluir cargas de trabajo después del descubrimiento y volver a incluirlas si desea agregar protección contra ransomware. No se le facturarán las cargas de trabajo excluidas.

Para obtener más información, consulte link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-start-discover.html#exclude-workloads["Excluir cargas de trabajo"^].



==== Marcar alertas como en revisión

Ransomware Resilience ahora le permite marcar alertas como "En revisión". Utilice la etiqueta "En revisión" para mejorar la claridad en todo su equipo al clasificar y gestionar amenazas de ransomware activas.

Para obtener más información, consulte link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-use-alert.html["Administrar alertas en Ransomware Resilience"^].



=== Cloud Volumes ONTAP



==== Opción de facturación preferida para Cloud Volumes ONTAP

Ahora puede seleccionar una opción de facturación preferida para calcular su uso y excedentes de Cloud Volumes ONTAP . Desde la disponibilidad limitada del modelo de licencias Bring Your Own Licenses (BYOL) el 25 de junio de 2025, NetApp ha agregado métodos de cobro preferidos en la sección *Licencias y suscripciones* de la NetApp Console. Puede utilizar su suscripción anual al mercado para la facturación y los excedentes o el modelo BYOL existente como opción preferida. Esto le brinda la flexibilidad de elegir el método de cobro que mejor se adapte a la estrategia financiera y los patrones de uso de su organización.

https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/concept-licensing-charging.html#billing-preferences-and-overages["Preferencias de facturación y excedentes"^].



== 10 de diciembre de 2025



=== Configuración y administración de la consola



==== Agente de consola 4.2.0

La versión 4.2.0 admite tanto el modo estándar como el modo restringido.

Esta versión del agente de consola incluye mejoras de seguridad, correcciones de errores y las siguientes características:

.Compatibilidad con Google Cloud Infrastructure Manager
NetApp ahora utiliza Google Cloud Infrastructure Manager (IM) en lugar de Google Cloud Deployment Manager para implementar agentes y administrarlos en Google Cloud. Este cambio se realizó porque Google dejará de usar link:https://docs.cloud.google.com/deployment-manager/docs/deprecations["Administrador de implementación en la nube"].

* Cualquier agente nuevo 4.2.0 y superior usa Infrastructure Manager y debe actualizar los permisos de la cuenta de usuario y de la cuenta de servicio utilizados para la implementación. link:https://docs.netapp.com/us-en/console-setup-admin/reference-permissions-gcp.html#gcp-permissions-change-log["Ver el registro de cambios de permisos."^]
* Cuando implementa un agente, el sistema también crea un depósito de Google Cloud para almacenar archivos de implementación.


.Comprobaciones de configuración mejoradas para los agentes de la consola
* El agente de consola ahora busca puntos finales obsoletos al realizar una verificación de configuración. Si no ha actualizado a la nueva lista de puntos finales para 4.0.0 o superior, las instalaciones tendrán éxito si el sistema puede acceder a la lista de puntos finales anterior. link:https://docs.netapp.com/us-en/console-setup-admin/reference-networking-saas-console-previous.html#update-endpoint-list["Obtenga más información sobre los puntos finales necesarios para los agentes de consola."^]
* Ejecute comprobaciones de configuración en los agentes de consola instalados desde la consola o la consola de mantenimiento del agente para verificar la conectividad y solucionar problemas. link:https://docs.netapp.com/us-en/console-setup-admin/task-troubleshoot-agent.html#verify-network-access["Aprenda a ejecutar comprobaciones de configuración en agentes de la consola."^]


.Descargue directamente el software del agente desde la NetApp Console
Cuando necesite instalar manualmente un agente, puede acceder al software del agente directamente desde la NetApp Console , además del sitio de soporte de NetApp . link:https://docs.netapp.com/us-en/console-setup-admin/task-install-agent-on-prem.html#install-the-console-agent-manually["Aprenda cómo descargar el software del agente de la consola directamente desde la NetApp Console."^]



==== Administración de la NetApp Console

Esta versión incluye lo siguiente:

.Capacidad de configurar notificaciones para credenciales que expiran
Establecer notificaciones para el vencimiento de credenciales en cuentas de servicio y federaciones. Elija entre siete o 30 días. La consola muestra notificaciones y envía correos electrónicos a los usuarios con el rol apropiado. Los administradores de la organización reciben notificaciones de la cuenta de servicio. Los administradores de la organización, los administradores de la federación y los espectadores de la federación reciben notificaciones de la federación.

.Los inicios de sesión locales no están disponibles después de habilitar la federación
Después de activar la federación para una organización de la consola, los usuarios no pueden usar inicios de sesión locales y se les envía a inicios de sesión de federación.

.Mejoras de usabilidad para las páginas de administración de almacenamiento
Ahora es más fácil ver y administrar información detallada sobre sus sistemas locales de ONTAP (y FSx para ONTAP) desde las páginas de administración de almacenamiento.

* La página * Discoverable systems* separa la información resumida de la visualización en pestañas de los sistemas disponibles, lo que facilita la visualización de información completa acerca de los sistemas detectables.




=== Clústeres ONTAP locales



==== Mejoras de usabilidad al visualizar sistemas ONTAP desde la NetApp Console (solo en modo estándar)

La página *Sistemas* en la NetApp Console tiene mejoras para mayor claridad y facilidad de uso al administrar volúmenes y clústeres. Estas actualizaciones alinean más de cerca la experiencia con System Manager para las versiones más nuevas de ONTAP y simplifican la navegación.

.Capacidad de clúster incluida para versiones de ONTAP 9.5 y superiores (solo modo estándar de consola)
La página *Sistemas > Descripción general* muestra el tamaño del clúster junto con la versión de ONTAP para los clústeres que ejecutan ONTAP 9.5 y versiones posteriores.

Para la NetApp Console en modo restringido o las versiones de ONTAP 9.5 y anteriores, la información del volumen aprovisionado permanece sin cambios.

.La pestaña Volúmenes en la página Sistemas tiene como opción predeterminada la vista de cuadrícula si tiene más de 20 clústeres ONTAP locales
Cuando tiene más de 20 clústeres ONTAP locales administrados en NetApp Console, la pestaña *Volumen* toma como valor predeterminado la vista de cuadrícula para facilitar la navegación. La vista de tarjeta está deshabilitada.

Este cambio se aplica únicamente al modo estándar y a las versiones 9.6 y superiores de ONTAP .



== 09 de diciembre de 2025



=== Recuperación ante desastres



==== Retención de la jerarquía de carpetas

De forma predeterminada, Disaster Recovery conserva la jerarquía del inventario de VM (estructura de carpetas) en caso de conmutación por error. Si el destino de recuperación no tiene la carpeta requerida, Disaster Recovery la crea.

Ahora puede anular esta configuración designando una nueva carpeta de VM principal o desmarcando la opción **Conservar jerarquía de carpetas original**.

Para obtener más información, consulte link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/drplan-create.html["Crear un plan de replicación"].



==== Actualización optimizada del agente de consola

La recuperación ante desastres ahora admite un proceso optimizado para utilizar múltiples agentes de consola en un entorno de trabajo. Para cambiar entre agentes de consola, debe editar la configuración de vCenter, redescubrir las credenciales y actualizar los planes de replicación para usar el nuevo agente de consola.

Para obtener más información, consulte link:https://docs.netapp.com/us-en/data-services-disaster-recovery/reference/switch-console-agent.html["Agentes de la consola Switch"].



== 08 de diciembre de 2025



=== Copia de seguridad y recuperación



==== Mejoras en la vista previa de las cargas de trabajo de VMware

La versión preliminar de las cargas de trabajo de VMware presenta las siguientes capacidades mejoradas:

* Ahora puede restaurar copias de seguridad e instantáneas en una ubicación alternativa. Esto es útil si desea administrar versiones de una máquina virtual en diferentes implementaciones de VMware vCenter, hosts VMware ESXi o almacenes de datos de VMware.


link:br-use-vmware-restore.html["Obtenga más información sobre cómo restaurar máquinas virtuales VMware con NetApp Backup and Recovery"].

* Ahora puede restaurar discos virtuales VMware específicos (imágenes VMDK) desde una ubicación principal o secundaria, lo que permite un control más granular sobre la restauración de datos de VM.


link:br-use-vmware-restore-vmdks-from-backups.html["Obtenga más información sobre cómo restaurar discos virtuales de VMware con NetApp Backup and Recovery"].



=== Clasificación de datos



==== Versión 1.49

Esta versión de Clasificación de datos incluye correcciones de errores y las siguientes actualizaciones:

.Supervise las métricas y el rendimiento en el panel de control de salud
La clasificación de datos ahora proporciona un panel de control de monitoreo de estado, que permite monitorear en tiempo real sus recursos e información sobre el uso de memoria, uso de disco, utilización de disco y más. Con la información del panel de monitoreo de estado, puede revisar la infraestructura de su implementación y obtener información para optimizar el almacenamiento y el rendimiento.

Para obtener más información, consulte link:https://docs.netapp.com/us-en/data-services-data-classification/task-health-monitor.html["Monitorear la salud de la clasificación de datos"].

.Rendimiento de carga mejorado
Se ha mejorado el rendimiento de carga de todas las páginas en Clasificación de datos para crear una experiencia de usuario más eficiente.



=== Resiliencia frente al ransomware



==== El bloqueo de extensiones está habilitado a nivel de carga de trabajo

Cuando habilita el bloqueo de extensiones, ahora se habilita en el nivel de carga de trabajo en lugar de en el nivel de máquina virtual de almacenamiento.



==== Editar el estado de alerta de comportamiento del usuario

Ransomware Resilience ahora le permite editar el estado de las alertas de comportamiento del usuario. Puede descartar y resolver alertas manualmente.

Para obtener más información, consulte link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-use-alert.html["Administrar alertas en Ransomware Resilience"^].



==== Compatibilidad con múltiples agentes de consola

Ransomware Resilience ahora admite el uso de múltiples agentes de consola para administrar los mismos sistemas.

Para obtener más información sobre los agentes de consola, consultelink:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-start-setup.html["Crear un agente de consola"] .



=== Cloud Volumes ONTAP



==== Capacidad para mejorar el rendimiento de los discos SSD Premium v2 en Azure

Ahora puede mejorar el rendimiento de los discos administrados SSD Premium v2 en Azure modificando los parámetros de IOPS y rendimiento. Al utilizar esta capacidad, puede optimizar el rendimiento de almacenamiento de sus sistemas en función de los requisitos de su carga de trabajo.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-manage-perf-params-azure.html["Administrar el rendimiento de los discos SSD v2 Premium para Cloud Volumes ONTAP en Azure"^].



==== Cobro por exceso de licencias Essentials simplificado

Para los contratos anuales/ofertas privadas del mercado Cloud Volumes ONTAP , los cálculos de excedente para las licencias Essentials ahora están alineados con los paquetes Bring Your Own License (BYOL). Anteriormente, los excedentes se facturaban a tarifas de mercado por hora para el paquete Essentials exacto. Ahora bien, si su contrato anual de Marketplace incluye varios paquetes Essentials, la NetApp Console cobra los excedentes de un paquete Essentials contra la capacidad disponible de un paquete Essentials de mayor precio en su suscripción. Esto simplifica los cálculos de excedente para los paquetes Essentials y garantiza una transición sin problemas de la licencia BYOL a un modelo basado en suscripción.

https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/concept-licensing-charging.html#how-overages-are-charged-for-essentials-licenses["Cómo se cobran los excedentes de las licencias Essentials"^]



==== Compatibilidad con la serie de tamaños de Azure Edsv6

A partir de Cloud Volumes ONTAP 9.17.1, puede implementar máquinas virtuales de la serie Azure Edsv6 a través de la NetApp Console para nuevas instancias de Cloud Volumes ONTAP . Cloud Volumes ONTAP 9.17.1 y versiones posteriores solo admitirán máquinas virtuales de segunda generación para nuevas implementaciones. Estas máquinas de segunda generación son compatibles con las últimas tecnologías, como la Interfaz de firmware extensible unificada (UEFI), los sistemas Azure Boost y NVMe. Son ideales para sistemas y aplicaciones que hacen un uso intensivo de la memoria y que necesitan almacenamiento local rápido, como servidores de bases de datos y motores de análisis.

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-azure.html#supported-configurations-by-license["Configuraciones compatibles con Cloud Volumes ONTAP en Azure"^]



=== Keystone

Nuevas mejoras en el panel de Keystone en la NetApp Console:



==== Etiqueta de capacidad de ráfaga acumulada renombrada

La etiqueta *Capacidad de ráfaga acumulada* pasa a llamarse *Ráfaga acumulada*.



== 1 de diciembre de 2025



=== Recuperación ante desastres



==== Compatibilidad con Google Cloud VMware Engine mediante Google Cloud NetApp Volumes

NetApp Disaster Recovery ahora es compatible con Google Cloud VMware Engine mediante Google Cloud NetApp Volumes para operaciones de migración, conmutación por error, recuperación y prueba. Esta integración permite flujos de trabajo de recuperación ante desastres sin inconvenientes entre entornos locales y Google Cloud.

Asegúrese de revisar ellink:https://docs.netapp.com/us-en/data-services-disaster-recovery/get-started/dr-prerequisites.html["prerrequisitos"] ylink:https://docs.netapp.com/us-en/data-services-disaster-recovery/release-notes/dr-limitations.html["limitaciones"] para Google Cloud.



== 27 de noviembre de 2025



=== Google Cloud NetApp Volumes



==== Cambios en las credenciales de Google Cloud Platform

A medida que los clientes configuran y autorizan más sistemas Google Cloud NetApp Volumes , la forma en que se administran las credenciales ha cambiado.

Las credenciales de los sistemas NetApp Volumes ahora se almacenan en un backend de Google Cloud, como el servicio Cloud Key Management o similar, y las credenciales de suplantación de cuenta de servicio se utilizan al crear un nuevo sistema.



== 24 de noviembre de 2025



=== Keystone

Nuevas mejoras en el panel de Keystone en la NetApp Console:



==== Identificación de seguimiento para suscripciones con brecha de cobertura

En el cuadro de notificación *Complete su cobertura* en *Monitoreo > Monitores de alerta*, cada suscripción ahora muestra su ID de seguimiento junto al número de suscripción.



== 17 de noviembre de 2025



=== Amazon FSX para ONTAP



==== El administrador del sistema está disponible al usar un enlace de AWS Lambda.

La interfaz del administrador del sistema ONTAP se puede utilizar con un enlace AWS Lambda para realizar operaciones avanzadas de ONTAP . Esto proporciona una alternativa al uso de un agente de consola con System Manager para administrar un sistema de archivos FSx para ONTAP directamente desde la consola. link:https://docs.netapp.com/us-en/workload-fsx-ontap/links-overview.html["Aprenda a usar enlaces para operaciones avanzadas de ONTAP"^]



== 11 de noviembre de 2025



=== Amazon FSX para ONTAP



==== Compatibilidad con la replicación entre sistemas ONTAP locales y sistemas de archivos FSx para ONTAP

La replicación de datos está disponible entre un sistema ONTAP local y un sistema de archivos FSx para ONTAP desde la página Sistemas de la NetApp Console .

link:https://docs.netapp.com/us-en/storage-management-fsx-ontap/use/task-manage-fsx-systems.html#replicate-data["Replicar datos"]



== 10 de noviembre de 2025



=== Licenses and subscriptions



==== Gestionar preferencias de facturación

Ahora puede configurar y administrar las *preferencias de facturación* directamente en la NetApp Console. Esta mejora permite a los administradores definir y ver cómo se facturan el uso de la capacidad, las renovaciones y los costos en las licencias directas de NetApp , las suscripciones al mercado en la nube y el acuerdo Keystone .

Para obtener más información, consulte lalink:https://docs.netapp.com/us-en/console-licenses-subscriptions/concept-billing-preferences.html["Documentación de preferencias de facturación"^] .



=== Configuración y administración de la consola



==== Agente de consola 4.1.0

Esta versión del agente de consola incluye mejoras de seguridad, correcciones de errores y las siguientes características:

La versión 4.1.0 está disponible para el modo estándar y el modo restringido.

.Indicadores de estado del agente renombrados
Se renombraron los indicadores de estado del agente de la consola de *Activo* e *Inactivo* a *Conectado* y *Desconectado* para que su propósito sea más claro.

.Compatibilidad con Red Hat Enterprise Linux (RHEL) 9.6 y Podman 5.4.0
Al instalar manualmente un agente de consola, el agente ahora admite RHEL 9.6 con Podman 5.4.0. Además, al usar RHEL 9 y versiones posteriores, NetApp admite podman-compose 1.5.0. link:https://docs.netapp.com/us-en/console-setup-admin/task-install-agent-on-prem.html["Ver requisitos del sistema operativo"].



==== Administración de la NetApp Console

Esta versión incluye lo siguiente:

.Nueva dirección de correo electrónico para las notificaciones de la NetApp Console
La dirección de correo electrónico que envía notificaciones de NetApp Console ha cambiado de *service@console.bluexp.netapp.com* a *service@console.bluexp.netapp.com*. NetApp recomienda actualizar las reglas de correo electrónico para permitir *service@console.netapp.com* para garantizar que continúe recibiendo notificaciones por correo electrónico de la NetApp Console .



=== Clasificación de datos



==== Versión 1.48

Esta versión de Data Classification incluye correcciones de errores, mejoras de seguridad y mejoras de rendimiento.

.Mayor claridad en el progreso del escaneo
Las configuraciones de escaneo ahora incluyen información mejorada sobre la finalización del escaneo. Anteriormente, la barra de progreso solo se mostraba mientras el escaneo estaba en curso. Ahora, la barra de progreso permanece visible después de la finalización para confirmar que los escaneos se completaron correctamente. También puedes ver el número de archivos mapeados y escaneados.

Para obtener más información sobre la configuración de escaneo, consulte link:https://docs.netapp.com/us-en/data-services-data-classification/task-managing-repo-scanning.html#view-the-scan-status-for-your-repositories["Cambie la configuración del análisis de NetApp Data Classification para sus repositorios"^].



=== Recuperación ante desastres



==== Soporte de conmutación por error en cascada

Ahora puede configurar una relación en cascada en ONTAP y utilizar cualquiera de las ramas de esa relación de replicación para la recuperación ante desastres.



==== Reducción de la compatibilidad con hardware de VMware durante el registro

La función de Recuperación ante Desastres ahora permite degradar el hardware de VMware a una versión anterior de vSphere durante el registro. Esto resulta útil cuando el host ESX de origen ejecuta una versión posterior a la del sitio de recuperación ante desastres.

Para obtener más información, consulte link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/drplan-create.html#select-vcenter-servers["Crear un plan de replicación en NetApp Disaster Recovery"].



==== Apagado correcto

La recuperación ante desastres ahora apaga las máquinas virtuales de forma controlada en lugar de apagarlas bruscamente. Si una máquina virtual tarda más de diez minutos en apagarse, el sistema de recuperación ante desastres la apaga.



==== Soporte para scripts previos a la copia de seguridad

Ahora puedes inyectar scripts personalizados en el flujo de trabajo de conmutación por error para que se ejecuten antes de crear una copia de seguridad. La creación de scripts previos a la copia de seguridad le permite controlar el estado de la máquina virtual antes de que se replique una instantánea y preparar una máquina virtual para una transición. Por ejemplo, puede inyectar un script que desmonte un montaje NFS que se volverá a montar utilizando un script diferente después de la conmutación por error.

Para obtener más información, consulte link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/drplan-create.html#select-vcenter-servers["Crear un plan de replicación en NetApp Disaster Recovery"].



=== Resiliencia frente al ransomware

Esta versión incluye mejoras generales.



=== Cloud Volumes ONTAP



==== Compatibilidad mejorada con NVMe-TCP

Anteriormente, al implementar instancias de Cloud Volumes ONTAP a través de NVMe-TCP, era necesario obtener y aplicar manualmente las licencias NVMe antes de la implementación. Con esta actualización, Cloud Volumes ONTAP ahora instala automáticamente las licencias NVMe necesarias durante la implementación, lo que simplifica el proceso de configuración.

Para las implementaciones NVMe-TCP existentes que carecen de licencias, Cloud Volumes ONTAP aplica las licencias automáticamente. Debe reiniciar el sistema para que las licencias surtan efecto.

Para obtener más información, consulte https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/concept-client-protocols.html#nvme-tcp["Protocolos de cliente compatibles con Cloud Volumes ONTAP: NVMe-TCP"^] .



=== Keystone

Nuevas mejoras en el panel de Keystone en la NetApp Console:



==== Complete su casilla de notificación de cobertura

La pestaña *Monitores de alertas* en la página *Monitoreo* incluye un cuadro de notificación *Complete su cobertura* que aparece cuando existen brechas de cobertura. Esta casilla muestra las suscripciones a las que les falta capacidad o que están próximas a vencer, y los monitores que no tienen suscripción. Puede solucionar estos problemas añadiendo suscripciones a los monitores existentes, creando nuevos monitores o eliminando los monitores que no se utilicen. Para obtener más información, consulte link:https://docs.netapp.com/us-en/keystone-staas/integrations/monitoring-alert-monitors.html#manage-coverage-gaps["Gestionar las brechas de cobertura para los monitores de alertas"].
