---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, bluexp, cloud volumes ontap, licenses, digital wallet, subscriptions, cloud backup, cloud tiering, data sense, ransomware, connector, agent, amazon fsx for ontap, azure netapp files, cloud sync, e-series, google cloud, disaster recovery, backup and recovery, classification, copy and sync, edge cache, edge caching, volume caching, ontap clusters, alerts, identity and access management, iam, recovery, netapp console, console' 
summary: Obtenga información sobre los cambios más recientes en las características y los servicios de datos que forman parte de la NetApp Console. 
---
= Cambios recientes en la NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Obtenga información sobre los cambios más recientes en las características y los servicios de datos que forman parte de la NetApp Console.  Para obtener un historial de lanzamiento completo, vaya alink:release-notes-index.html["conjunto completo de notas de la versión"] para cada servicio individual.

[NOTE]
====
Los siguientes servicios han quedado obsoletos:

Almacenamiento en caché perimetral:: El servicio de almacenamiento en caché de borde se eliminó el 7 de agosto de 2024.
Kubernetes:: El soporte para descubrir y administrar clústeres de Kubernetes se eliminó el 7 de agosto de 2024.
Informes de migración:: El servicio de informes de migración se eliminó el 7 de agosto de 2024.
Resiliencia operativa:: Las funciones de resiliencia operativa se eliminaron el 22 de agosto de 2025.
Remediación:: El servicio de remediación se eliminó el 22 de abril de 2024.


====


[[03-august-2026]]
== 3 de agosto de 2026



[[well-architected-dashboard]]
=== Panel bien diseñado



==== Nombres de configuración actualizados para FSx for ONTAP en el panel de control de well-architected

El panel bien diseñado en NetApp Console ahora muestra nombres actualizados de configuración de almacenamiento para FSx for ONTAP para mejorar la claridad y la coherencia.

La siguiente tabla muestra los nombres de configuración antiguos y sus correspondientes nombres de configuración nuevos en el panel de control de well-architected.

[cols="1,1"]
|===
| Nombre de la configuración anterior | Nuevo nombre de configuración 


| Programar copias de seguridad de volúmenes | Copias de seguridad de volúmenes 


| Límite de capacidad del SSD | Margen de capacidad del SSD 


| Límite de capacidad de archivos | Margen de capacidad de archivos 


| Fiabilidad de los datos de retención a largo plazo | Etiquetas de políticas de replicación 


| Instantáneas locales programadas | Política de SnapVault 


| Elimina las copias de seguridad innecesarias | Caducidad de la copia de seguridad 


| Eliminar instantáneas innecesarias | Caducidad de la instantánea 


| Capacidad no aprovechada del SSD | Capacidad de SSD sobredimensionada 


| Dispositivos de bloque inactivos | Dispositivos de bloque inactivos (LUN) 


| Optimiza el coste total de propiedad (TCO) al trasladar los datos inactivos a niveles | Jerarquización de datos inactivos 


| Informes sobre la capacidad lógica de los volúmenes | Informes de capacidad visibles para el host 


| Reequilibrio de volúmenes FlexGroup | Reequilibrar volúmenes FlexGroup 


| FlexVol reequilibrio de volúmenes | Reequilibrar volúmenes FlexVol 


| Modo de escritura de la relación de caché | FlexCache modo de escritura 


| Optimiza el tamaño del volumen de caché | FlexCache tamaño de la réplica 


| Acceso no autorizado al volumen | Acceso no autorizado a un volumen iSCSI 


| ARP/AI desactivado | Protección contra el ransomware (ARP/IA) 
|===


==== Corregir, descartar y reactivar configuraciones de Cloud Volumes ONTAP en Microsoft Azure

El panel bien estructurado en la NetApp Console ahora te permite corregir las recomendaciones de configuración para tus sistemas Cloud Volumes ONTAP.

También puedes excluir una o varias configuraciones del análisis de well-architected. Esto te permite ignorar configuraciones específicas que no se aplican a tu entorno.

Si deseas incluir más adelante una configuración que hayas descartado, puedes reactivarla en el panel de control de well-architected. Esto restaura la configuración en el análisis y te permite obtener recomendaciones y soluciones para ella.

link:https://docs.netapp.com/us-en/console-well-architected/cvo/\improve-configurations-cvo.html["Corregir, descartar y reactivar configuraciones de Cloud Volumes ONTAP en Microsoft Azure"]



[[ransomware-resilience]]
=== Resiliencia frente al ransomware



==== Compatibilidad de SAN para Google Cloud NetApp Volumes (versión preliminar)

Ransomware Resilience ya es compatible con las cargas de trabajo SAN de Google Cloud NetApp Volumes, lo que te permite detectar ataques de ransomware basados en cifrado para cargas de trabajo SAN. La compatibilidad con SAN en Google Cloud NetApp Volumes se encuentra actualmente en vista previa.

Para más información, consulta link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/concept-ransomware-resilience.html#supported-systems["sistemas compatibles"^] y link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-reference-limitations.html#azure-netapp-files-limitations["Almacenamiento SAN en Ransomware Resilience"^].



==== Interfaz optimizada para el bloqueo de usuarios

Ransomware Resilience ofrece ahora una experiencia de usuario simplificada para bloquear usuarios y gestionar los usuarios bloqueados. Con esta actualización, puedes revisar y modificar fácilmente qué usuarios has bloqueado. Debes haber configurado link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/concept-user-behavior.html["detección de actividad del usuario"^] para bloquear usuarios.

Para obtener más información, consulta link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-users-manage.html#manage-blocked-users["Usuarios bloqueados gestionados"^].



[[cloud-volumes-ontap]]
=== Cloud Volumes ONTAP



==== Integración de Cloud Volumes ONTAP con Microsoft OneLake

Cloud Volumes ONTAP ya admite la integración con https://learn.microsoft.com/en-us/fabric/onelake/onelake-overview["Microsoft OneLake"^] en versión preliminar pública. Puedes integrar Cloud Volumes ONTAP con https://community.fabric.microsoft.com/["Microsoft Fabric"^] usando https://learn.microsoft.com/en-us/fabric/onelake/onelake-overview["Microsoft OneLake"^] para que los datos NAS existentes de Cloud Volumes ONTAP estén disponibles para los servicios de análisis e IA de Microsoft, como Power BI, Azure AI Search, OpenAI y Microsoft Copilot. La integración no requiere movimiento ni duplicación de datos. La integración usa https://docs.netapp.com/us-en/ontap/s3-multiprotocol/index.html["ONTAP S3 multiprotocolo"^] acceso para conectar Cloud Volumes ONTAP a un lakehouse de Microsoft Fabric ya existente.

.Artículos y recursos relacionados:
* https://www.netapp.com/blog/optimize-ai-analytics-microsoft-onelake/?utm_content=nativelink&utm_medium=internal&utm_source=linkedin&utm_campaign=b2d-port-all-na-ww-digi-blog-1747859361262&es_id=956c739202["NetApp blog: Optimiza la IA y el análisis con Microsoft OneLake y NetApp Cloud Volumes ONTAP"^]
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-azure-onelake.html["Integra los sistemas Cloud Volumes ONTAP con Microsoft OneLake para IA y analítica"^]
* https://www.netapp.com/media/160786-na-1263-netapp-cloud-volumes-ontap-azure-onelake.pdf["Integración de Cloud Volumes ONTAP con Microsoft OneLake - Ficha técnica"^]




==== Corregir, descartar y reactivar configuraciones de Cloud Volumes ONTAP en Microsoft Azure

El panel bien estructurado en la NetApp Console ahora te permite corregir las recomendaciones de configuración para tus sistemas Cloud Volumes ONTAP.

También puedes excluir una o varias configuraciones del análisis de well-architected. Esto te permite ignorar configuraciones específicas que no se aplican a tu entorno.

Si deseas incluir más adelante una configuración que hayas descartado, puedes reactivarla en el panel de control de well-architected. Esto restaura la configuración en el análisis y te permite obtener recomendaciones y soluciones para ella.

* link:https://docs.netapp.com/us-en/console-well-architected/cvo/improve-configurations-cvo.html["Corregir, descartar y reactivar configuraciones de Cloud Volumes ONTAP en Microsoft Azure"^]




[[27-july-2026]]
== 27 de julio de 2026



[[ransomware-resilience]]
=== Resiliencia frente al ransomware



==== Estandariza los grupos de protección según la carga de trabajo y el tipo de sistema

La función Ransomware Resilience ahora exige que los grupos de protección incluyan únicamente un tipo de carga de trabajo y un tipo de sistema. Cuando creas un nuevo grupo de protección, debes especificar tanto el tipo de carga de trabajo (file system o block) como el sistema para la carga de trabajo. Esta mejora asegura que la estrategia de protección frente al ransomware elegida para el grupo de protección se pueda aplicar correctamente a todas las cargas de trabajo del grupo.

Si ya tienes grupos de protección en los que se mezclan tipos de sistema y de cargas de trabajo, puedes seguir utilizándolos, pero no puedes añadir cargas de trabajo al grupo de protección.

Para obtener más información, consulta link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-protection-group.html["Crear un grupo de protección"^].



==== Mejora de los simulacros de preparación

Ransomware Resilience ahora te permite realizar simulacros de preparación según el tipo de ataque. Ransomware Resilience detecta cinco tipos de ataques, y puedes realizar simulacros de preparación para cada uno de ellos con el fin de simular el proceso de ataque y recuperación para comprender tu preparación ante un ataque de ransomware.

Para obtener más información, consulta link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-start-simulate.html["Realiza un simulacro de preparación"^].



==== Pausar o eliminar un sistema SIEM

Ransomware Resilience incluye ahora opciones en la interfaz de usuario para pausar o eliminar un sistema SIEM. Esta mejora facilita desactivar temporalmente el sistema para la resolución de problemas o el mantenimiento, o eliminarlo por completo.

Para obtener más información, consulta link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-siem.html#disable-a-siem-system["Desactivar un sistema SIEM"^].



[[23-july-2026]]
== 23 de julio de 2026



[[cloud-volumes-ontap]]
=== Cloud Volumes ONTAP



==== Compatibilidad con la región de Chile Central en Azure

Ya puedes implementar Cloud Volumes ONTAP 9.12.1 GA y versiones posteriores en la región Chile Central (chilecentral) en Azure. Se admiten los siguientes tipos de implementación:

* Clúster de un solo nodo
* HA en una única zona de disponibilidad usando almacenamiento con redundancia local (LRS)
* HA en varias zonas de disponibilidad mediante almacenamiento con redundancia por zona (ZRS)


Para consultar la lista de todas las regiones compatibles, visita https://bluexp.netapp.com/cloud-volumes-global-regions["Mapa de regiones globales en Azure"^].



[[20-july-2026]]
== 20 de julio de 2026



[[well-architected-dashboard]]
=== Panel bien diseñado



==== Presentamos el panel bien arquitectado en NetApp Console

El panel de control well-architected en NetApp Console ofrece una vista única de tus sistemas de almacenamiento y configuraciones en todas las cuentas y regiones. El panel de control proporciona información y recomendaciones para ayudarte a alcanzar la excelencia operativa. Puedes ver el estado well-architected de tus configuraciones, los problemas de configuración organizados según los pilares del marco well-architected para el tipo de almacenamiento que usas, y una lista de problemas de configuración y recomendaciones.

Obtén más información sobre el link:https://docs.netapp.com/us-en/console-well-architected/learn-well-architected-dashboard.html["panel bien diseñado"].

El panel bien arquitectado en la Consola está disponible para los siguientes sistemas de almacenamiento:

* link:https://docs.netapp.com/us-en/console-well-architected/fsx/configuration-analysis-fsx.html["Amazon FSx for NetApp ONTAP"]
* link:https://docs.netapp.com/us-en/console-well-architected/cvo/configuration-analysis-cvo.html["Cloud Volumes ONTAP en Microsoft Azure"]




==== Crea tus propias reglas personalizadas

Redacta reglas personalizadas en lenguaje sencillo para asegurarte de que tus sistemas cumplan con las normas de tu organización y las mejores prácticas de NetApp. Prueba las reglas con una simulación y luego programa que se ejecuten en todos tus entornos.

https://docs.netapp.com/us-en/console-well-architected/learn-custom-rules.html["Obtén más información sobre las reglas personalizadas"]



[[ransomware-resilience]]
=== Resiliencia frente al ransomware



==== Configura SIEM mediante webhooks

Ransomware Resilience ya permite configurar un sistema de gestión de información y eventos de seguridad (SIEM) mediante webhooks en la interfaz de usuario de Ransomware Resilience. Con webhooks, puedes usar tu sistema SIEM preferido para organizar tu monitoreo de ransomware.

Para más información, consulta link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-siem.html["Configura un sistema SIEM"^].



==== Alertas por correo electrónico para respuestas automáticas a eventos de actividad de usuarios

Ransomware Resilience ahora envía notificaciones por correo electrónico cuando se activan respuestas automáticas por eventos de actividad de usuario, mejorando la claridad y la visibilidad de Ransomware Resilience y de las actividades de ransomware.

Para más información, consulta link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-automate-user-activity.html["Automatiza las respuestas a las alertas sobre la actividad de los usuarios"^].



[[cloud-volumes-ontap]]
=== Cloud Volumes ONTAP



==== Presentamos la incorporación simplificada de Cloud Volumes ONTAP desde AWS Marketplace

NetApp introduce un proceso de puesta en marcha simplificado para Cloud Volumes ONTAP desde AWS Marketplace, reduciendo los pasos manuales y la fricción en la puesta en marcha.

Anteriormente, para implementar Cloud Volumes ONTAP desde AWS Marketplace era necesario pasar por varias pantallas y configurar manualmente los roles, las políticas y las credenciales. Esto hacía que la puesta en marcha fuera lenta y propensa a errores.

El nuevo proceso de incorporación simplifica tu transición de una suscripción en el marketplace a un entorno de Cloud Volumes ONTAP totalmente operativo con las siguientes características:

. Suscripción a la ficha específica de Cloud Volumes ONTAP en AWS Marketplace: te suscribes a la ficha independiente de Cloud Volumes ONTAP en AWS Marketplace, compras una suscripción y configuras tu cuenta de AWS (si aún no tienes una).
. Ruta guiada en la NetApp Console: Configuras tu cuenta en la NetApp Console y la Console te incorpora automáticamente al recorrido de implementación, mostrando la ruta guiada en el lado derecho. Si necesitas salir de la Console, puedes reanudar el recorrido guiado más adelante.
. Asociar tu suscripción: Puedes asociar automáticamente tu suscripción con la Consola, evitando los pasos manuales de vincularla tú mismo.
. Implementación del agente de la consola con configuración de credenciales de AWS: puedes crear automáticamente los roles de AWS necesarios. El proceso implementa una pila de AWS CloudFormation en tu cuenta de AWS con los roles y políticas necesarios para que los revises, luego los asocia con la NetApp Console, eliminando la configuración manual de IAM. Luego continúas con la configuración del agente, la red y los ajustes del grupo de seguridad para comenzar la implementación del agente.
. Implementa un nuevo sistema Cloud Volumes ONTAP en AWS: navega directamente al asistente  `Quick create` para una implementación más rápida y sencilla de Cloud Volumes ONTAP.


.Enlaces relacionados
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-quick-deploy-aws.html["Implementa Cloud Volumes ONTAP con Quick create"^]
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/whats-new.html#flexible-billing-for-cloud-volumes-ontap-and-data-services-in-aws["Facturación flexible para Cloud Volumes ONTAP y servicios de datos en AWS"^]




==== Análisis de configuración well-architected para Cloud Volumes ONTAP en Azure

La NetApp Console ya admite el análisis de configuración well-architected para los sistemas Cloud Volumes ONTAP que se ejecutan en Microsoft Azure. La NetApp Console analiza tus implementaciones diariamente y proporciona un estado well-architected, información detallada y recomendaciones para ayudarte a mantener sistemas que se ajusten a las prácticas recomendadas de NetApp y al marco well-architected.

El panel de control bien estructurado muestra el número total de sistemas analizados y clasifica sus recursos por configuración y nivel de gravedad. Si eres administrador del sistema, puedes ver recomendaciones sobre cualquier problema de configuración dentro de tu organización directamente desde el panel de control de la Console y descargar un informe CSV con todas las recomendaciones. Las configuraciones se clasifican según:

* *Fiabilidad*: Garantiza que las cargas de trabajo funcionen de forma correcta y constante, incluso en caso de interrupciones.
* *Seguridad*: Protege los datos, los sistemas y los activos mediante evaluaciones de riesgos y mitigación.
* *Excelencia operativa*: Optimiza la arquitectura para maximizar el valor empresarial.
* *Optimización de costes*: Reduce y optimiza los costes para generar un mayor valor empresarial.


.Enlaces relacionados
* https://docs.netapp.com/us-en/console-well-architected/cvo/configuration-analysis-cvo.html["Análisis de la configuración de Cloud Volumes ONTAP"^]
* https://docs.netapp.com/us-en/console-well-architected/cvo/improve-configurations-cvo.html["Implementa configuraciones de sistema Cloud Volumes ONTAP bien diseñadas"^]




[[keystone]]
=== Keystone

Nuevas mejoras en el panel de Keystone en la NetApp Console:



==== Ver la fecha de vencimiento de la suscripción y el estado de la renovación automática

La columna *Días hasta el vencimiento de la suscripción* de la tabla de suscripciones (*Almacenamiento > Keystone > Suscripciones*) muestra ahora un icono junto a la fecha de vencimiento. El color del icono indica la proximidad de la fecha de vencimiento cuando la renovación automática está desactivada: verde (>120 días), naranja (91–120 días), rojo (<90 días) o gris (caducada). En el caso de las suscripciones con la renovación automática activada, se muestra un icono de renovación automática que indica que la suscripción se renovará automáticamente al final del periodo actual. El estado es de solo lectura y refleja las condiciones de tu contrato. Una vez que abres una suscripción, estos iconos aparecen en el encabezado de los detalles de la suscripción en las pestañas *Consumo actual*, *Tendencia de consumo*, *Cronología de la suscripción* y *Activos*, lo que te permite ver el estado de vencimiento y renovación mientras navegas.

Para obtener más información, consulta https://docs.netapp.com/us-en/keystone-staas/integrations/subscriptions-tab.html["Ver detalles sobre tus suscripciones a Keystone"].



[[15-july-2026]]
== 15 de julio de 2026



[[console-setup-and-administration]]
=== Configuración y administración de la consola



==== Agente de Console 4.9.0

La versión 4.9.0 es compatible tanto con el modo estándar como con el modo restringido.

Esta versión del agente de la Console incluye mejoras de seguridad y correcciones de errores.



==== Administración de la NetApp Console

NetApp Console 4.9.0 administración incluye la siguiente nueva función.

.Compatibilidad con el acceso basado en roles para Cloud Volumes ONTAP
La consola admite el control de acceso basado en roles para Cloud Volumes ONTAP.

link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-cvo-roles.html["Más información sobre el control de acceso basado en roles para Cloud Volumes ONTAP"^].



[[amazon-fsx-for-ontap]]
=== Amazon FSX para ONTAP



==== Eliminación de cargas de trabajo de GenAI de Workloads en la NetApp Console

La carga de trabajo GenAI se ha eliminado de Cargas de trabajo en la NetApp Console.



[[digital-advisor]]
=== Asesor digital



==== Aviso de obsolescencia de Wellness Review

La función Wellness Review ha quedado obsoleta y ya no está disponible en Digital Advisor desde julio de 2026.

Si tienes alguna pregunta o quieres enviarnos tus comentarios, mailto:ng-activeiq-feedback@netapp.com[contacta con el equipo de Active IQ].



[[14-july-2026]]
== 14 de julio de 2026



[[cloud-volumes-ontap]]
=== Cloud Volumes ONTAP



==== Cloud Volumes ONTAP 9.19.1

La versión candidata al lanzamiento (RC) de Cloud Volumes ONTAP 9.19.1 está disponible únicamente en Google Cloud para la actualización a la versión 9.19.1 de disponibilidad general (GA).

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/["Más información sobre esta versión de Cloud Volumes ONTAP"^].



==== Compatibilidad con las máquinas virtuales de Google Cloud de última generación en Cloud Volumes ONTAP HA

Con la versión 9.19.1, NetApp traslada las implementaciones de alta disponibilidad (HA) de Cloud Volumes ONTAP de las máquinas virtuales N2 a las máquinas virtuales de la serie C3 de Google Cloud de última generación para ofrecer una experiencia más rápida y escalable.


NOTE: Esta compatibilidad solo se aplica a las implementaciones de alta disponibilidad (HA) en una única zona de disponibilidad (AZ).

Ahora puedes aprovechar las máquinas virtuales de la serie C3 al implementar Cloud Volumes ONTAP 9.19.1 y versiones posteriores en Google Cloud. Estas máquinas ofrecen un rendimiento mejorado y límites de capacidad más altos. Utilizan Google Virtual NIC (gVNIC) y discos Hyperdisk Balanced para un rendimiento dinámico en cargas de trabajo intensivas.

Si tu sistema Cloud Volumes ONTAP ejecuta la versión 9.19.1 o posterior, los paquetes preconfigurados que usas para implementaciones sencillas en AZ únicas utilizan automáticamente máquinas virtuales C3, y te permiten personalizar los parámetros de IOPS y rendimiento según las necesidades de tu carga de trabajo. De manera similar, al crear agregados, puedes añadir discos Zonal Hyperdisk Balanced para lograr un mejor rendimiento y escalabilidad en Google Cloud. También puedes seleccionar las variantes LSSD de las máquinas de la serie C3 para compatibilidad predeterminada con Flash Cache.

Ten en cuenta estos puntos:

* En tus implementaciones de Cloud Volumes ONTAP no puedes cambiar máquinas virtuales C3 por máquinas virtuales de la serie N2, ni viceversa. Sin embargo, puedes cambiar el tipo de instancia entre las diferentes variantes de la familia C3.
+

NOTE: El cambio de tipo de instancia dentro de la familia C3 puede tardar más según la cantidad de discos de datos conectados. Planifica tu configuración con antelación para evitar impactos en el rendimiento.

* Al cambiar el tipo de instancia, si seleccionas c3-standard-44 o c3-standard-88 y sus variantes con SSD local (LSSD) como máquina virtual de destino, se aplica automáticamente el nivel de red de salida del servicio de red de Google _Tier-1_. Si vuelves a cambiar a cualquier otra variante de C3, el nivel de red de salida se establece en _Standard_.
+

NOTE: Cambiar el nivel de red de salida a _Tier-1_ conlleva costes adicionales. Planifica la implementación y la actualización en consecuencia.

* Si seleccionas las variantes LSSD de C3, Flash Cache se activa de forma predeterminada. No puedes cambiar entre las variantes LSSD de C3 en tu implementación de Cloud Volumes ONTAP, incluso si la variante de destino es compatible con Flash Cache.
* En tus máquinas virtuales C3, puedes añadir volúmenes tanto a agregados nuevos como a los ya existentes.
* Al replicar un sistema Cloud Volumes ONTAP con un tipo de máquina virtual N2 a un tipo de máquina virtual C3, el tipo de disco se establece por defecto en Hyperdisk Balanced.
* Puedes modificar los ajustes de IOPS y ancho de banda al añadir agregados a través de la NetApp Console o mediante la  `PUT /gcp/ha/aggregates/{workingEnvironmentId}/{aggregateName}` API.


https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-gcp.html["Configuraciones compatibles para Cloud Volumes ONTAP en Google Cloud"^]

https://docs.cloud.google.com/compute/docs/general-purpose-machines#c3_series["Google documentos: serie de máquinas C3"^]



==== Implementación simplificada de Cloud Volumes ONTAP en Google Cloud

Ahora puedes utilizar el asistente *Creación rápida* para implementar Cloud Volumes ONTAP en Google Cloud, tanto en configuraciones de un solo nodo como de alta disponibilidad (HA). Este proceso optimizado reduce el número de pasos, establece los valores predeterminados automáticamente en una sola página y minimiza la navegación para que la implementación sea más rápida y sencilla.

.Enlaces relacionados
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-quick-deploy-gcp.html["Implementa Cloud Volumes ONTAP en Google Cloud con Quick create"^]
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-deploying-gcp.html["Implementa Cloud Volumes ONTAP usando las opciones avanzadas en Google Cloud"^]




==== Presentación de los roles de acceso para Cloud Volumes ONTAP

NetApp introduce roles de gestión de identidades y accesos (IAM) para Cloud Volumes ONTAP, lo que permite el control de acceso basado en roles (RBAC) para mejorar la seguridad y facilitar el cumplimiento normativo. Los usuarios pueden seguir iniciando sesión en la NetApp Console utilizando sus credenciales actuales para las operaciones de Cloud Volumes ONTAP. Sin embargo, ahora la autenticación se enruta a través de la federación de identidades, lo que permite al administrador de la Console tener un control más detallado sobre estas funciones. Cada usuario debe tener uno de los siguientes roles para realizar cualquier operación en Cloud Volumes ONTAP. Sin un rol, los usuarios no pueden ver ni acceder a las instancias de Cloud Volumes ONTAP.

* *Cloud Volumes ONTAP viewer*: Otorga acceso de solo lectura a las pantallas y pestañas de Cloud Volumes ONTAP. Ciertas pantallas y botones de acción están deshabilitados en este rol.
* *Cloud Volumes ONTAP operator*: Permite realizar tareas de gestión cotidianas, como añadir volúmenes, gestionar el almacenamiento y configurar la replicación.
* *Administrador de Cloud Volumes ONTAP*: Ofrece acceso completo a todas las operaciones de Cloud Volumes ONTAP.


El administrador de la consola asigna roles a los usuarios de Cloud Volumes ONTAP desde *Administración > Identidad*. Los permisos de los roles se basan en la organización a la que pertenece el usuario y se aplican a todos los sistemas de Cloud Volumes ONTAP de dicha organización.

Cloud Volumes ONTAP aplica el modelo RBAC mediante una caché local de los permisos de cada usuario, que se actualiza automáticamente una vez cada hora. Cuando se asigna un nuevo rol a un usuario o se modifica su rol actual, el cambio puede tardar hasta una hora en surtir efecto, después de lo cual se habilitan todos los flujos de trabajo permitidos por los roles.


NOTE: Cuando se implementa un agente de Console por primera vez, o cuando se actualiza un agente de Console existente a la versión 4.9.0 o posterior, un proceso de configuración inicial único asigna automáticamente roles de Cloud Volumes ONTAP a todos los usuarios existentes de la organización. Este proceso puede tardar hasta 30 minutos en completarse. Y cuando termina, Console asigna los roles adecuados a los usuarios existentes.

Las funciones de Cloud Volumes ONTAP aplican a los entornos de Amazon Web Services (AWS), Microsoft Azure (Azure) y Google Cloud.

.Enlaces relacionados
* https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["NetApp roles de acceso a la consola"^]
* https://docs.netapp.com/us-en/console-setup-admin/reference-iam-cvo-roles.html["Roles de acceso de Cloud Volumes ONTAP en NetApp Console"^]




[[13-july-2026]]
== 13 de julio de 2026



[[backup-and-recovery]]
=== Copia de seguridad y recuperación



==== Compatibilidad mejorada con múltiples compartimentos para todas las cargas de trabajo

NetApp Backup and Recovery ahora permite proteger las cargas de trabajo dentro de un sistema con hasta 100 buckets repartidos entre diferentes proveedores de nube. Se requiere ONTAP 9.19.1 o una versión posterior para admitir más de 6 buckets por sistema.

Para obtener más información sobre NetApp Backup and Recovery, consulta https://docs.netapp.com/us-en/data-services-backup-recovery/concept-backup-to-cloud.html["Obtén información sobre NetApp Backup and Recovery"].



[[disaster-recovery]]
=== Recuperación ante desastres



==== Actualizaciones de Kubernetes

Disaster Recovery ha introducido los siguientes cambios para las cargas de trabajo basadas en Kubernetes:



===== Gestiona Trident Protect desde el menú «Sitios»

Disaster Recovery ahora permite gestionar Trident Protect directamente desde el menú Sites de la interfaz de usuario de Disaster Recovery. Puedes actualizar Trident Protect o eliminarlo de Disaster Recovery, lo que agiliza la gestión de tus recursos de Kubernetes.

Para más información, consulta link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/manage.html["Gestionar sitios"^].



==== Actualizaciones de VMware

Recuperación ante desastres ha introducido los siguientes cambios para las cargas de trabajo basadas en VMware:



===== Conmutación por error en almacenes de datos vacíos

Los planes de replicación que incluyen almacenes de datos vacíos ahora pueden someterse a una conmutación por error con éxito sin excluirlos del plan ni forzar la conmutación por error. Durante la conmutación por error, Disaster Recovery monta automáticamente el almacén de datos vacío en el sitio de recuperación ante desastres, permitiendo añadir máquinas virtuales y protegerlas para las operaciones de conmutación de vuelta.

Para más información, consulta link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/failover.html["Conmutación por error a un sitio remoto"^].



===== vCenter mapeo automático de red

Ahora puedes configurar las relaciones de asignación de red a nivel de vCenter (es decir, fuera del cuadro de diálogo del plan de replicación). Una vez configurado, Disaster Recovery aplica automáticamente estas asignaciones de red cuando añades o editas un plan de replicación, lo que agiliza la gestión de los planes de replicación.

La recuperación ante desastres sigue admitiendo modificaciones específicas por plan. Las asignaciones de red existentes definidas en un plan de replicación pueden seguir editándose por red; estas asignaciones tienen prioridad sobre las definiciones a nivel de vCenter.



==== Restricción del rol de visor de Disaster Recovery

Se ha eliminado la posibilidad de ver la pestaña Upgrade System del rol Disaster Recovery viewer. Este cambio adapta el rol a la experiencia más adecuada para los usuarios con acceso de solo lectura. link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-disaster-rec-roles.html["Conoce los roles y permisos de usuario en NetApp Disaster Recovery"^].



==== Mejoras del rendimiento del sistema

Recuperación ante desastres ha introducido cambios para reducir el consumo de recursos del sistema y mejorar el rendimiento en todas las operaciones.



[[07-july-2026]]
== 07 de julio de 2026



[[ransomware-resilience]]
=== Resiliencia frente al ransomware



==== Excluir rutas de archivos de las alertas de comportamiento de los usuarios

NetApp Ransomware Resilience permite excluir rutas de archivos específicas de las alertas de supervisión del comportamiento de los usuarios. Puedes excluir rutas de archivos si sabes que no corren riesgo o si estás trabajando con archivos en un volumen que podría activar alertas.

Para más información, consulta link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-users-manage.html["Excluir rutas de archivos de las alertas"^].



==== Plantilla ARM para Microsoft Sentinel

Ransomware Resilience ahora ofrece una plantilla de Azure Resource Manager (ARM) para conectarse a Microsoft Sentinel como SIEM, ofreciendo un método secundario para facilitar la implementación.

Para más información, consulta link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-siem.html["Conéctate a un SIEM para la detección y el análisis de amenazas"^].



[[29-june-2026]]
== 29 de junio de 2026



[[ransomware-resilience]]
=== Resiliencia frente al ransomware



==== Respuestas automáticas a las alertas de actividad de los usuarios

Ransomware Resilience ahora permite automatizar la creación de instantáneas y el bloqueo de usuarios cuando se genera una alerta de actividad de usuario. Con las respuestas automatizadas, puedes bloquear a un usuario en cuanto se genere una advertencia y crear una instantánea para la recuperación, lo que permite una respuesta más rápida sin intervención manual.

Para más información, consulta link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-automate-user-activity.html["Automatiza las respuestas a las alertas sobre la actividad de los usuarios"^].



[[digital-advisor]]
=== Asesor digital



==== Revisión del estado de GraphQL: migración y mejoras en la precisión de los datos

El módulo «Health Check» se ha mejorado con una mayor precisión de los datos y recomendaciones de versiones alineadas con los estándares de vigencia. Como parte de esta versión, se ha migrado de la Public API a GraphQL, lo que ofrece un mejor rendimiento, consultas flexibles y soporte a largo plazo.



===== Software recomendado

Las mejoras recomendadas de software en el módulo Health Check ahora proporcionan datos más precisos y coherentes.

* Los recuentos de estantes y unidades que aparecen en la sección de firmware muestran los valores exactos por sistema y ya no incluyen los recuentos de HA Pair.
* Las recomendaciones sobre la versión mínima y la más reciente ahora se calculan a nivel de clúster en función de la versión efectiva del clúster, en línea con los estándares de actualización; antes, estas recomendaciones se calculaban a nivel de nodo.




===== AutoSupport dependencia de datos

Debido a mejoras en el backend, las vistas de adopción y de software recomendado de AutoSupport se basan en los datos más recientes de AutoSupport. Esto podría afectar tu vista actual de las siguientes maneras:

[cols="30,70"]
|===
| Escenario | Sistemas afectados 


| No se muestran datos | Sistemas que no han enviado un AutoSupport desde octubre de 2025 


| Valores obsoletos | Sistemas que no han enviado un AutoSupport en los últimos 30 días 
|===
Vuelve a ejecutar AutoSupport en los sistemas afectados que se indican más arriba para restaurar los datos actuales en las vistas de Health Check.



[[keystone]]
=== Keystone

Nuevas mejoras en el panel de Keystone en la NetApp Console:



==== Ver la distribución de licencias de ADP para las suscripciones de MetroCluster

Ya está disponible una nueva subpestaña *Distribución de licencias* en la pestaña *Protección avanzada de datos (ADP)*, que te da visibilidad sobre el uso de licencias de ADP en todos tus clústeres asociados de MetroCluster. Para obtener más información, consulta https://docs.netapp.com/us-en/keystone-staas/integrations/adp-tab.html["Consulta el consumo y la salud de tus suscripciones Keystone MetroCluster"].



==== Ver el estado de la protección contra ransomware de tus volúmenes

La pestaña *Volúmenes en clústeres* de *Activos* ahora incluye una columna *Estado de ARP* que muestra si la Protección Autónoma contra Ransomware (ARP) está activada o desactivada para cada volumen, dándote visibilidad sobre tu postura de protección contra ransomware en todos los activos gestionados. Para saber más sobre ARP, consulta https://docs.netapp.com/us-en/ontap/anti-ransomware/["Protección autónoma contra el ransomware (ARP) en ONTAP"^].



==== Envía tus comentarios a través de la pestaña Feedback

Ahora puedes enviar tus comentarios desde cualquier pantalla del panel de control de Keystone utilizando la nueva pestaña *Comentarios*, situada en la esquina inferior derecha de la pantalla. Al hacer clic en ella, se abre un panel en el que puedes compartir tu experiencia y enviar comentarios directamente a NetApp.



==== Mejora las alertas sobre el uso de la capacidad y la caducidad de las suscripciones

Los monitores generados por el sistema ahora ofrecen alertas más granulares sobre el uso de la capacidad y la expiración de la suscripción.

Para el vencimiento de la suscripción, ahora las alertas se activan en cinco umbrales: 180, 90, 60, 30 y 7 días antes del vencimiento, con la gravedad aumentando de informativa a crítica a medida que se acerca la fecha.

Para el uso de la capacidad, el umbral de alerta de picos ahora se basa en el porcentaje de picos comprometido de tu suscripción en lugar de un 20% fijo. Por ejemplo, si tu pico comprometido es del 40%, la alerta crítica se activa al 140% del uso de la capacidad comprometida.

Para obtener más información, consulta https://docs.netapp.com/us-en/keystone-staas/integrations/monitoring-alert-monitors.html["Ver y crear monitores de alertas para suscripciones de Keystone"].



[[15-june-2026]]
== 15 de junio de 2026



[[console-setup-and-administration]]
=== Configuración y administración de la consola



==== Lanzamiento de private mode (4.7.0)

Ya está disponible una nueva versión del modo privado para descargar desde la https://mysupport.netapp.com/site/downloads["Sitio de soporte de NetApp"^]

La versión 4.7.0 incluye actualizaciones de los siguientes componentes y servicios de NetApp Console.

[cols="3*"]
|===
| Componente o servicio | Versión incluida en este lanzamiento | Cambios desde la versión anterior en modo privado 


| Agente de consola | 4.7.0 | Ve al https://docs.netapp.com/us-en/console-setup-admin/whats-new.html#2026-05-11.html["Novedades en la página de NetApp Console"^] y revisa los cambios incluidos para las versiones 4.7.0. 


| NetApp Backup and Recovery | 5.4.0 (08 de junio de 2026) | Ve a https://docs.netapp.com/us-en/data-services-backup-recovery/whats-new.html["novedades en la página de NetApp Backup and Recovery"^]. 


| NetApp Data Classification | 1.54.0 (11 de mayo de 2026) | Ve a https://docs.netapp.com/us-en/data-services-data-classification/whats-new.html["novedades en la página de clasificación de NetApp"^]. 
|===


[[backup-and-recovery]]
=== Copia de seguridad y recuperación



==== Mejoras en cargas de trabajo de Kubernetes

En esta versión, las cargas de trabajo de Kubernetes introducen las siguientes mejoras:

* *Trident Protect 26.06*: Esta versión incluye Trident Protect 26.06.
* *Omitir la creación de aplicaciones durante la restauración*: Ahora puedes omitir la creación automática de objetos de recursos personalizados de aplicaciones durante las operaciones de restauración. Esto reduce las entradas innecesarias en el inventario de la aplicación.
* *Restaurar reclamaciones de volúmenes persistentes de máquinas virtuales*: Al restaurar aplicaciones basadas en máquinas virtuales, ahora puedes restaurar reclamaciones de volúmenes persistentes individuales sin restaurar toda la máquina virtual, lo que hace que la recuperación sea más rápida cuando discos o volúmenes específicos se ven afectados por corrupción o pérdida de datos.
* *Mejoras en el monitor de tareas*: El monitor de tareas ahora ofrece una mayor visibilidad de las tareas de protección de Kubernetes. Puedes consultar información detallada sobre el estado de las tareas y subtareas, y ver el almacenamiento de destino que utiliza cada una.


Para obtener más información sobre cómo proteger las cargas de trabajo de Kubernetes, consulta https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["Descripción general de la protección de cargas de trabajo de Kubernetes"].



[[11-june-2026]]
== 11 de junio de 2026



[[cloud-volumes-ontap]]
=== Cloud Volumes ONTAP



==== Compatibilidad con una nueva región de Azure en Cloud Volumes ONTAP

Ya puedes implementar Cloud Volumes ONTAP 9.12.1 GA y versiones posteriores en una o varias zonas de disponibilidad de Azure en la región de Malaysia West (malaysiawest). Esto incluye soporte tanto para implementaciones de un solo nodo como de alta disponibilidad (HA).

Para ver la lista de todas las regiones, consulta https://bluexp.netapp.com/cloud-volumes-global-regions["Mapa de regiones globales en Azure"^].



[[08-june-2026]]
== 08 de junio de 2026



[[console-setup-and-administration]]
=== Configuración y administración de la consola



==== Agente de Console 4.8.0

La versión 4.8.0 es compatible tanto con el modo estándar como con el modo restringido.

Esta versión del agente de la Console incluye mejoras de seguridad y correcciones de errores.



==== Administración de la NetApp Console

Esta versión incluye mejoras de seguridad y correcciones de errores.



[[backup-and-recovery]]
=== Copia de seguridad y recuperación



==== Mejoras en las cargas de trabajo de ONTAP Volumes

En esta versión, las cargas de trabajo de ONTAP Volumes introducen la siguiente mejora:

*Soporte para almacenamiento en la nube compatible con S3*: NetApp Backup and Recovery para cargas de trabajo de Volumes ahora admite la realización de copias de seguridad en almacenamiento en la nube compatible con S3.

Para obtener más información sobre la protección de las cargas de trabajo de ONTAP Volumes, consulta https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html["Descripción general de la protección de cargas de trabajo de ONTAP Volumes"].



==== Mejoras en las cargas de trabajo de Hyper-V

En esta versión, las cargas de trabajo Hyper-V introducen las siguientes mejoras:

* *Mejoras en la restauración de archivos y carpetas en una máquina virtual invitada*: Ahora puedes restaurar archivos y carpetas de una instantánea en el almacenamiento primario o secundario a una máquina virtual de Windows invitada. Esta función ahora es compatible con VMs CIFS y SAN.
* *Los grupos de protección ahora utilizan la programación según la zona horaria del host*: Los grupos de protección ahora utilizan la zona horaria del host de Hyper-V. Los grupos de protección creados antes de que se introdujera la programación según la zona horaria del host siguen utilizando la hora configurada anteriormente (normalmente UTC). Para actualizar estos grupos de protección para que utilicen la zona horaria del host de Hyper-V, tienes que volver a crear las programaciones. Consulta https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protection-groups.html["Crear y gestionar grupos de protección para cargas de trabajo de Hyper-V"] para obtener más información.


Para más detalles sobre la protección de cargas de trabajo Hyper-V, consulta https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protect-overview.html["Descripción general de la protección de cargas de trabajo de Hyper-V"].



==== Mejoras en las cargas de trabajo de VMware

En esta versión, VMware workloads introduce la siguiente mejora:

* *Los grupos de protección ahora utilizan la programación basada en la zona horaria del host*: Los grupos de protección ahora usan la zona horaria del servidor VMware vCenter que los aloja. Los grupos de protección creados antes de que se introdujera la programación basada en la zona horaria del host siguen ejecutándose en su zona horaria configurada previamente (normalmente UTC). Para usar la zona horaria de vCenter, tienes que volver a crear las programaciones. Consulta https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protection-groups.html["Crear y gestionar grupos de protección para cargas de trabajo de VMware"] para más información.


Para obtener detalles sobre cómo proteger las cargas de trabajo de VMware, consulta https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protect-overview.html["Descripción general de la protección de cargas de trabajo de VMware"].



[[data-classification]]
=== Clasificación de datos



==== Mejoras generales

Esta versión de Data Classification incluye mejoras de seguridad y mejoras en el rendimiento.



[[disaster-recovery]]
=== Recuperación ante desastres



==== Actualizaciones de Kubernetes

Disaster Recovery ha introducido los siguientes cambios para las cargas de trabajo basadas en Kubernetes:



===== Prueba la compatibilidad de la conmutación por error para las cargas de trabajo de Kubernetes

Recuperación ante desastres ahora admite la prueba del proceso de conmutación por error para cargas de trabajo de Kubernetes. Probar la conmutación por error te permite validar los planes de recuperación ante desastres. Cuando terminas la prueba, puedes limpiar la conmutación por error de prueba para que el sistema limpie automáticamente los recursos de prueba, reduzca la sobrecarga y asegure la coherencia de tu entorno.

Para más información, consulta link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/failover.html#test-the-failover-process["Probar el proceso de conmutación por error"^].



===== Pruebas programadas de failover

Ahora puedes automatizar las pruebas de recuperación ante desastres programando pruebas de conmutación por error. Puedes programar pruebas de conmutación por error recurrentes para validar continuamente los planes de recuperación sin intervención manual, lo que ayuda a mantener la confianza en los objetivos de recuperación y a cumplir los requisitos de cumplimiento.

Para más información, consulta link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/manage.html#manage-replication-plans["Gestiona los planes de replicación"^].



===== Descubrimiento programado de cargas de trabajo Kubernetes

Con la detección programada, puedes controlar la frecuencia con la que Disaster Recovery busca nuevas cargas de trabajo de Kubernetes. Puedes configurar los intervalos de detección para alinearlos con tu cadencia operativa, reduciendo la sobrecarga innecesaria del sistema mientras aseguras que las nuevas cargas de trabajo se detectan y protegen a tiempo.

Para más información, consulta link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/sites-add.html#edit-the-site-and-customize-the-discovery-schedule["Personaliza el calendario de descubrimiento"^].



==== Actualizaciones de VMware



===== Protección para almacenes de datos vacíos

Disaster Recovery permite ahora configurar la protección de almacenes de datos que no contienen ninguna máquina virtual (VM). Cualquier VM añadida posteriormente al almacén de datos es detectada automáticamente por Disaster Recovery, momento en el que tienes que proporcionar link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/sites-add.html#add-subnet-mapping-for-a-vcenter-site["información de mapeo"^].

Cuando agregas un datastore vacío a un plan de protección, debes eliminar el datastore del plan de protección antes de realizar una conmutación por error o realizar una conmutación por error forzada. Para más información, consulta link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/failover.html["Conmutación por error a un sitio remoto"^].



===== Restaurar almacenes de datos previamente excluidos a un plan de protección

Los almacenes de datos que anteriormente estaban excluidos de la protección ahora se pueden volver a incluir. Esta mejora proporciona una mayor flexibilidad al gestionar y actualizar tus configuraciones de recuperación ante desastres con el tiempo.

Para más información, consulta link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/manage.html["Administra sitios, grupos de recursos y planes de replicación"^].



===== Conmutación por error más rápida para almacenes de datos basados en VMFS

Disaster Recovery ha mejorado el rendimiento de la conmutación por error para los datastores basados en VMFS. Las operaciones de reexploración del Host Bus Adapter (HBA) y de montaje del datastore ahora se ejecutan en paralelo, lo que reduce los tiempos totales de conmutación por error y minimiza el tiempo de inactividad durante los eventos de recuperación.

Para obtener más información sobre las conmutaciones por error, consulta link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/failover.html["Fail over con recuperación ante desastres"^].



[[ransomware-resilience]]
=== Resiliencia frente al ransomware



==== Mayor flexibilidad para las estrategias de protección

Ransomware Resilience ofrece ahora más flexibilidad a la hora de elegir estrategias de detección de ransomware. Anteriormente, todas las estrategias de protección contra ransomware tenían que incluir la detección de cifrado. Ahora, puedes activar una estrategia de protección contra ransomware solo con la detección del comportamiento del usuario.

Las estrategias de protección pueden incluir tanto la detección de cifrado _como_ la detección de comportamientos sospechosos de los usuarios. El bloqueo de extensiones de archivo también puede añadirse a cualquier estrategia de protección.

Si desactivas parte de la estrategia de protección para una política existente, cualquier alerta existente creada bajo la iteración anterior de la política solo puede marcarse como "Resuelta" y no como "Descartada". Por ejemplo, si tenías una estrategia de protección que incluía detección de cifrado y comportamiento sospechoso del usuario pero desactivas la detección de cifrado, solo puedes resolver una alerta de cifrado existente para esa carga de trabajo.

Para obtener más información, consulta link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-use-protect.html["Protege las cargas de trabajo con estrategias de protección de NetApp Ransomware Resilience"^].



==== Mejoras en el playbook SOAR

Los manuales SOAR de resiliencia al ransomware ahora proporcionan pasos de corrección después de que hayas bloqueado a un usuario o puesto un volumen fuera de línea. Ahora puedes volver a poner un volumen en línea y desbloquear a un usuario si la acción no se consideró una amenaza de ransomware.

link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/reference-soar.html["Integra un playbook SOAR"^].



[[cloud-volumes-ontap]]
=== Cloud Volumes ONTAP



==== Soporte para nuevas instancias EC2 para Cloud Volumes ONTAP en AWS

Cloud Volumes ONTAP 9.16.1 y versiones posteriores son compatibles con las familias de instancias EC2 M6id y M6idn tanto para despliegues de nodo único como de alta disponibilidad (HA) nuevos y existentes en AWS. Estas instancias de 6ª generación ofrecen una potencia de procesamiento más rápida, mayores capacidades de red y un rendimiento superior en comparación con los sistemas de propósito general de 5ª generación.

* *Instancias M6id*: Proporcionan un equilibrio entre computación y memoria con almacenamiento local NVMe de alta velocidad y baja latencia. Todos los tamaños de instancia M6id admiten Flash Cache. Estas instancias son muy adecuadas para cargas de trabajo como el registro de datos y el procesamiento de medios.
* *Instancias M6idn*: Proporcionan las mismas capacidades de almacenamiento local NVMe que las instancias M6id. Todos los tamaños de instancia M6idn admiten Flash Cache.


No recomendamos los tipos de instancia m6id.xlarge, m6id.2xlarge, m6idn.xlarge y m6idn.2xlarge de menor tamaño para cargas de trabajo de alto rendimiento o con uso intensivo de memoria. Para estas cargas de trabajo, usa un tipo de instancia con mayor número de núcleos y más memoria.

Para más información, consulta https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-aws.html["Configuraciones compatibles para Cloud Volumes ONTAP en AWS"^].



[[03-june-2026]]
== 03 de junio de 2026



[[lifecycle-planning]]
=== Planificación del ciclo de vida



==== Actualización de los nombres de las funciones de planificación del ciclo de vida

Las siguientes funciones de planificación del ciclo de vida tienen cambios de nombre:

* La función «Tech Refresh» ahora se llama *System Refresh*. Descubre cómo https://docs.netapp.com/us-en/console-lifecycle-planning/use/tech-refresh.html["evaluar una actualización del sistema"].
* La función «Aumentar capacidad» ahora se llama *Ampliación de almacenamiento*. Descubre cómo https://docs.netapp.com/us-en/console-lifecycle-planning/use/capacity-add.html["ampliar el almacenamiento"].
* La función «Renovaciones» ahora se llama *Renovaciones de soporte*. Descubre cómo https://docs.netapp.com/us-en/console-lifecycle-planning/support/task-support-registration.html["registrarse para soporte"].




[[digital-advisor]]
=== Asesor digital



==== Actualización del nombre del widget de Digital Advisor

Las siguientes funciones de Digital Advisor han cambiado de nombre:

* La función Tech Refresh ahora se llama System Refresh. Aprende cómo link:https://docs.netapp.com/us-en/active-iq/evaluate-tech-refresh.html["evaluar una actualización del sistema"].
* La función de ampliación de capacidad se llama ahora Storage Expansion. Conoce más sobre link:https://docs.netapp.com/us-en/active-iq/concept_getting_started_2.html["Widgets de Digital Advisor"].
* La función Renovaciones se llama ahora Support Renewals. Conoce más sobre link:https://docs.netapp.com/us-en/active-iq/concept_getting_started_2.html["Widgets de Digital Advisor"].




[[26-may-2026]]
== 26 de mayo de 2026



[[ransomware-resilience]]
=== Resiliencia frente al ransomware



==== Compatibilidad con Google Cloud NetApp Volumes (vista previa)

Ransomware Resilience ahora admite la creación de grupos de protección para cargas de trabajo en sistemas Google Cloud NetApp Volumes, lo que te permite organizar varias cargas de trabajo bajo una política para agilizar la gestión.

Para más información, consulta link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-protection-group.html["Crear un grupo de protección en Ransomware Resilience"^].



[[25-may-2026]]
== 25 de mayo de 2026



[[keystone]]
=== Keystone

Nuevas mejoras en el panel de Keystone en la NetApp Console:



==== Mejora de la visualización de varias actualizaciones en el mismo día en la cronología de suscripción

El gráfico cronológico de suscripciones ahora muestra un número cuando se producen varias actualizaciones de suscripciones de distintos tipos en el mismo día, en lugar de iconos separados. Pasa el ratón por encima del número para ver todos los tipos de actualización de ese día. El informe descargado incluye una fila separada para cada actualización, dándote un registro completo de todos los cambios. Para obtener más información, consulta https://docs.netapp.com/us-en/keystone-staas/integrations/subscription-timeline.html["Ver la cronología de tus suscripciones a Keystone"].



[[18-may-2026]]
== 18 de mayo de 2026



[[ransomware-resilience]]
=== Resiliencia frente al ransomware



==== Compatibilidad con Google Cloud NetApp Volumes (vista previa)

Ransomware Resilience ahora es compatible con los sistemas de Google Cloud NetApp Volumes, lo que te permite detectar y responder eficazmente a las amenazas de ransomware en Google Cloud NetApp Volumes. Cuando realizas la detección, Ransomware Resilience muestra automáticamente las cargas de trabajo de los sistemas de Google Cloud NetApp Volumes. Cuando descubres los sistemas, aparecen en el panel de Ransomware Resilience. El soporte para Google Cloud NetApp Volumes en Ransomware Resilience está actualmente en vista previa.

Para obtener más información, consulta link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/concept-ransomware-resilience.html["Conoce la resiliencia ante ransomware"^]. Para obtener información sobre el alcance de la asistencia de Google Cloud NetApp Volumes, consulta link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-reference-limitations.html["Limitaciones de la resistencia al ransomware"^].



==== Mejoras en la restauración limpia

La restauración limpia ahora admite informes. Con los informes, puedes revisar y evaluar las restauraciones limpias, guardando esta información sin conexión como un archivo CSV.

La restauración limpia también permite ahora detener el análisis. Si detienes el análisis, debes iniciar de nuevo la restauración limpia.

Para saber más sobre informes, consulta link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-use-reports.html["Descargar informes en Ransomware Resilience"^]. Para saber más sobre recuperación, consulta link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-clean-restore-recover.html["Recupera cargas de trabajo con una restauración limpia"^].



[[cloud-volumes-ontap]]
=== Cloud Volumes ONTAP



==== Implementación simplificada de Cloud Volumes ONTAP en Azure

Ahora puedes usar Quick create para implementar Cloud Volumes ONTAP en Azure tanto para configuraciones de nodo único como de alta disponibilidad (HA). Este proceso optimizado reduce el número de pasos en comparación con el método avanzado, establece automáticamente los valores predeterminados en una sola página y minimiza la navegación, lo que hace que la implementación sea más rápida y sencilla.

.Enlaces relacionados
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-quick-deploy-azure.html["Implementa Cloud Volumes ONTAP en Azure con Quick create"^]
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-deploying-otc-azure.html["Implementa Cloud Volumes ONTAP usando opciones avanzadas en Azure"^]




[[digital-advisor]]
=== Asesor digital



==== Revisión del bienestar

A partir de julio de 2026, la función Wellness Review dejará de estar disponible en Digital Advisor. Para cualquier consulta, envía un correo electrónico a mailto:ng-activeiq-feedback@netapp.com[[.underline]#ng-activeiq-feedback@netapp.com#].
