---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, bluexp, cloud volumes ontap, licenses, digital wallet, subscriptions, cloud backup, cloud tiering, data sense, ransomware, connector, agent, amazon fsx for ontap, azure netapp files, cloud sync, e-series, global file cache, google cloud, disaster recovery, backup and recovery, classification, copy and sync, edge cache, edge caching, volume caching, ontap clusters, alerts, identity and access management, iam, recovery, netapp console, console' 
summary: Obtenga información sobre los cambios más recientes en las características y los servicios de datos que forman parte de la NetApp Console. 
---
= Cambios recientes en la NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Obtenga información sobre los cambios más recientes en las características y los servicios de datos que forman parte de la NetApp Console.  Para obtener un historial de lanzamiento completo, vaya alink:release-notes-index.html["conjunto completo de notas de la versión"] para cada servicio individual.



== Funciones administrativas

En esta sección se describen las nuevas funciones relacionadas con las funciones de administración de la NetApp Console : organizaciones, identificación y acceso, agentes de la consola, credenciales del proveedor de nube y más.



== Alertas



== Amazon FSx para ONTAP



== Almacenamiento de Amazon S3



== Almacenamiento de blobs de Azure



== Azure NetApp Files



== Copia de seguridad y recuperación



== Clasificación de datos



== Cloud Volumes ONTAP



== Copiar y sincronizar



== Asesor digital



== Licenses and subscriptions



=== 6 de octubre de 2025



==== BlueXP ahora es NetApp Console

La NetApp Console, construida sobre la base BlueXP mejorada y reestructurada, proporciona una gestión centralizada del almacenamiento de NetApp y de los NetApp Data Services en entornos locales y en la nube a nivel empresarial, brindando información en tiempo real, flujos de trabajo más rápidos y una administración simplificada, que es altamente segura y compatible.

Para obtener más detalles sobre lo que ha cambiado, consulte lalink:https://docs.netapp.com/us-en/bluexp-relnotes/index.html["Notas de la versión de la NetApp Console"] .



=== 10 de marzo de 2025



==== Capacidad de eliminar suscripciones

Ahora puedes eliminar suscripciones de la billetera digital si te has dado de baja de ellas.



==== Ver la capacidad consumida para las suscripciones de Marketplace

Al ver las suscripciones PAYGO, ahora puedes ver la capacidad consumida de la suscripción.



=== 10 de febrero de 2025

La BlueXP digital wallet ha sido rediseñada para facilitar su uso y ahora ofrece gestión adicional de suscripciones y licencias.



==== Nuevo panel de descripción general

La página de inicio de la billetera digital tiene un panel actualizado de sus licencias de NetApp y suscripciones de Marketplace, con la capacidad de desglosar servicios específicos, tipos de licencias y acciones requeridas.



==== Configuración de suscripciones a credenciales

La BlueXP digital wallet ahora le permite configurar sus suscripciones con credenciales de proveedor. Normalmente esto se hace cuando se suscribe por primera vez a una suscripción de Marketplace o a un contrato anual. Anteriormente, cambiar las credenciales de la suscripción solo se podía hacer en la página Credenciales.



==== Asociar suscripciones con organizaciones

Ahora puedes actualizar la organización a la que está asociada una suscripción directamente desde la billetera digital.



==== Administración de licencias de Cloud Volume ONTAP

Ahora puede administrar las licencias de Cloud Volumes ONTAP a través de la página de inicio o la pestaña *Licencias directas*. Utilice la pestaña *Suscripciones del Marketplace* para ver la información de su suscripción.



=== 5 de marzo de 2024



==== BlueXP disaster recovery

La BlueXP digital wallet ahora le permite administrar licencias para la BlueXP disaster recovery. Puede agregar licencias, actualizar licencias y ver detalles sobre la capacidad autorizada.

https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-data-services-licenses.html["Aprenda a administrar licencias para los servicios de datos de BlueXP"]



=== 30 de julio de 2023



==== Mejoras en los informes de uso

Ahora están disponibles varias mejoras en los informes de uso de Cloud Volumes ONTAP :

* La unidad TiB ahora está incluida en el nombre de las columnas.
* Ahora se incluye un nuevo campo _node(s)_ para números de serie.
* Ahora se incluye una nueva columna _Tipo de carga de trabajo_ en el informe de uso de máquinas virtuales de almacenamiento.
* Los nombres de los entornos de trabajo ahora se incluyen en los informes de uso de volúmenes y máquinas virtuales de almacenamiento.
* El tipo de volumen _archivo_ ahora está etiquetado como _Principal (Lectura/Escritura)_.
* El tipo de volumen _secundario_ ahora está etiquetado como _Secundario (DP)_.


Para obtener más información sobre los informes de uso, consulte https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-capacity-licenses.html#download-usage-reports["Descargar informes de uso"] .



== Recuperación ante desastres



== Sistemas de la serie E



== Planificación del ciclo de vida



== Almacenamiento en caché perimetral

El servicio de almacenamiento en caché de borde se eliminó el 7 de agosto de 2024.



== Google Cloud NetApp Volumes



== Almacenamiento en la nube de Google



== Keystone



== Kubernetes

El soporte para descubrir y administrar clústeres de Kubernetes se eliminó el 7 de agosto de 2024.



== Informes de migración

El servicio de informes de migración se eliminó el 7 de agosto de 2024.



== Clústeres ONTAP locales



== Resiliencia operativa

Las funciones de resiliencia operativa se eliminaron el 22 de agosto de 2025.



== Resiliencia frente al ransomware



== Remediación

El servicio de remediación se eliminó el 22 de abril de 2024.



== Replicación



== Actualizaciones de software



== StorageGRID



== Nivelación de la nube



=== 6 de octubre de 2025



==== La BlueXP tiering ahora es NetApp Cloud Tiering

La BlueXP tiering ha cambiado su nombre a NetApp Cloud Tiering.



==== BlueXP ahora es NetApp Console

La NetApp Console, construida sobre la base BlueXP mejorada y reestructurada, proporciona una gestión centralizada del almacenamiento de NetApp y de los NetApp Data Services en entornos locales y en la nube a nivel empresarial, brindando información en tiempo real, flujos de trabajo más rápidos y una administración simplificada, que es altamente segura y compatible.

Para obtener más detalles sobre lo que ha cambiado, consulte lalink:https://docs.netapp.com/us-en/bluexp-relnotes/index.html["Notas de la versión de la NetApp Console"] .



=== 9 de agosto de 2023



==== Utilice un prefijo personalizado para el nombre del depósito

En el pasado, era necesario utilizar el prefijo "fabric-pool" predeterminado al definir el nombre del depósito, por ejemplo, _fabric-pool-bucket1_.  Ahora puedes usar un prefijo personalizado al nombrar tu bucket.  Esta funcionalidad solo está disponible cuando se agrupan los datos en Amazon S3. https://docs.netapp.com/us-en/bluexp-tiering/task-tiering-onprem-aws.html#prepare-your-aws-environment["Más información"] .



==== Busque un clúster en todos los conectores BlueXP

Si utiliza varios conectores para administrar todos los sistemas de almacenamiento en su entorno, es posible que algunos clústeres en los que desee implementar niveles estén en diferentes conectores.  Si no está seguro de qué conector administra un determinado clúster, puede buscar en todos los conectores mediante Cloud Tiering. https://docs.netapp.com/us-en/bluexp-tiering/task-managing-tiering.html#search-for-a-cluster-across-all-bluexp-connectors["Más información"] .



=== 4 de julio de 2023



==== Ajustar el ancho de banda para transferir datos inactivos

Cuando activa la organización en niveles en la nube, ONTAP puede usar una cantidad ilimitada de ancho de banda de red para transferir los datos inactivos de los volúmenes del clúster al almacenamiento de objetos.  Si nota que el tráfico en niveles afecta las cargas de trabajo normales de los usuarios, puede limitar la cantidad de ancho de banda que se puede usar durante la transferencia. https://docs.netapp.com/us-en/bluexp-tiering/task-managing-tiering.html#changing-the-network-bandwidth-available-to-upload-inactive-data-to-object-storage["Más información"] .



==== Evento de niveles que se muestra en el Centro de notificaciones

El evento de niveles "Asigne datos adicionales desde el clúster <nombre> al almacenamiento de objetos para aumentar la eficiencia del almacenamiento" ahora aparece como una notificación cuando un clúster está agrupando en niveles menos del 20 % de sus datos fríos, incluidos los clústeres que no están agrupando en niveles ningún dato.

Esta notificación es una "Recomendación" para ayudar a que sus sistemas sean más eficientes y ahorrar en costos de almacenamiento. Proporciona un enlace a la https://www.netapp.com/data-services/tiering/tco-calculator/["Calculadora de ahorro y costo total de propiedad de Cloud Tiering"^] para ayudarle a calcular sus ahorros de costos.



== Almacenamiento en caché de volumen



== Fábrica de carga de trabajo



=== 6 de octubre de 2025



==== BlueXP workload factory ahora NetApp Workload Factory

BlueXP ha sido renombrado y rediseñado para reflejar mejor el papel que desempeña en la gestión de su infraestructura de datos.  Como resultado, la BlueXP workload factory pasó a llamarse NetApp Workload Factory.



==== Integración de Ask Me con MCP

Ask Me, el asistente de inteligencia artificial de Workload Factory, está integrado con el Protocolo de contexto de modelo (MCP).  Al utilizar MCP, Ask Me interactúa de forma segura con entornos externos y consulta herramientas API para brindar respuestas adaptadas a su entorno de almacenamiento específico.



=== 5 de octubre de 2025



==== Nueva notificación para Almacenamiento

El servicio de notificación de NetApp Workload Factory incluye la notificación de problemas bien diseñados para el almacenamiento.

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["Notificaciones para NetApp Workload Factory"]



=== 9 de septiembre de 2025



==== Nueva notificación para Almacenamiento

El servicio de notificación de BlueXP workload factory incluye la notificación para la gestión automática de la capacidad de almacenamiento.

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["Notificaciones para la BlueXP workload factory"]
