= Agente de consola 4.3.0
:allow-uri-read: 




=== Agente de consola 4.3.0

La versión 4.3.0 admite tanto el modo estándar como el modo restringido.

Esta versión del agente de consola incluye mejoras de seguridad, correcciones de errores y las siguientes características:

.Capacidad para validar las conexiones de red de los agentes de la consola
Ahora puedes validar las conexiones de red de los agentes de Console conectados directamente desde la NetApp Console. Esta función te ayuda a verificar la conectividad y solucionar problemas con los agentes de Console. Esto se suma a la capacidad existente de ejecutar diagnósticos de red desde la línea de comandos de la consola de mantenimiento del agente de Console (CLI).

link:https://docs.netapp.com/us-en/console-setup-admin/task-troubleshoot-agent.html#verify-network-access["Aprende cómo ejecutar la configuración desde NetApp Console."]



=== Administración de la NetApp Console

Esta versión incluye lo siguiente:

.Acceso basado en roles para grupos federados en la NetApp Console
NetApp Console admite la asignación de roles a grupos federados (por ejemplo, grupos de Active Directory), lo que permite a los administradores automatizar la incorporación y salida de usuarios en función de la membresía del grupo en el proveedor de identidad (IdP) de la organización. Esta función reduce la sobrecarga administrativa y garantiza un acceso seguro y consistente al actualizar instantáneamente el acceso a la consola a medida que cambian las membresías del grupo.

link:https://docs.netapp.com/us-en/console-setup-admin/task-iam-manage-members-permissions.html#add-a-federated-group-to-your-organization["Aprenda cómo proporcionar acceso a un grupo federado a su organización."]

.Compatibilidad con la federación cuando la NetApp Console está en modo restringido
Ahora puede habilitar la federación para una organización de NetApp Console que esté en modo restringido. Esto permite a los usuarios iniciar sesión en la consola utilizando sus credenciales corporativas mientras mantienen los beneficios de seguridad del modo restringido.

.Modo de solo lectura
Puede configurar una organización de la NetApp Console en modo de solo lectura. En el modo de solo lectura, los usuarios pueden ver recursos y configuraciones, pero no pueden realizar cambios. Un administrador de organización o un superadministrador puede habilitar el modo de solo lectura para una organización. Cuando el modo de solo lectura está habilitado, los usuarios con roles administrativos deben elevar manualmente sus permisos para realizar cambios según sea necesario.

link:https://docs.netapp.com/us-en/console-setup-admin/task-enable-read-only-mode.html["Aprenda cómo habilitar el modo de solo lectura para una organización de consola."]

link:https://docs.netapp.com/us-en/console-setup-admin/task-user-settings.html["Aprenda cómo elevar su rol cuando su organización está en modo de solo lectura."]
