= Implementación simplificada de Cloud Volumes ONTAP en Azure
:allow-uri-read: 




=== Implementación simplificada de Cloud Volumes ONTAP en Azure

Ahora puedes usar Quick create para implementar Cloud Volumes ONTAP en Azure tanto para configuraciones de nodo único como de alta disponibilidad (HA). Este proceso optimizado reduce el número de pasos en comparación con el método avanzado, establece automáticamente los valores predeterminados en una sola página y minimiza la navegación, lo que hace que la implementación sea más rápida y sencilla.


NOTE: Si usas Creación rápida para desplegar un nuevo sistema Cloud Volumes ONTAP en Azure, la consola NetApp selecciona las credenciales de Azure por defecto. Puedes desplegar todos tus sistemas Cloud Volumes ONTAP usando las credenciales iniciales de Azure. Si quieres usar otra suscripción y/o credenciales, necesitas cambiar al despliegue en modo avanzado. Esta limitación se solucionará en una versión futura.

.Enlaces relacionados
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-quick-deploy-azure.html["Implementa Cloud Volumes ONTAP en Azure con Quick create"^]
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-deploying-otc-azure.html["Implementa Cloud Volumes ONTAP usando opciones avanzadas en Azure"^]

