= Mejoras en la BlueXP backup and recovery para aplicaciones (nativa de la nube)
:allow-uri-read: 




=== Mejoras en la BlueXP backup and recovery para aplicaciones (nativa de la nube)

* Base de datos de Microsoft SQL Server
+
** Admite copias de seguridad, restauración y recuperación de bases de datos de Microsoft SQL Server que residen en Amazon FSx for NetApp ONTAP
** Todas las operaciones se admiten únicamente a través de API REST.


* Sistemas SAP HANA
+
** Durante la actualización del sistema, el montaje y desmontaje automático de los volúmenes se realiza mediante flujos de trabajo en lugar de scripts.
** Admite la adición, eliminación, edición, eliminación, mantenimiento y actualización del host del complemento mediante la interfaz de usuario.






=== Mejoras en la BlueXP backup and recovery para aplicaciones (híbridas)

* Admite bloqueo de datos y protección contra ransomware.
* Admite el traslado de copias de seguridad desde StorageGrid al nivel de archivo
* Admite la realización de copias de seguridad de datos de aplicaciones MongoDB, MySQL y PostgreSQL desde sistemas ONTAP locales a Amazon Web Services, Microsoft Azure, Google Cloud Platform y StorageGRID.  Puede restaurar los datos cuando sea necesario.




=== Mejoras en la BlueXP backup and recovery para máquinas virtuales

* Compatibilidad con el modelo de implementación de proxy de conector

