= Nueva gestión de políticas para los datos de ONTAP
:allow-uri-read: 




=== Nueva gestión de políticas para los datos de ONTAP

Esta versión incluye la capacidad dentro de la interfaz de usuario de crear políticas de instantáneas personalizadas, políticas de replicación y políticas para copias de seguridad en el almacenamiento de objetos para datos de ONTAP .

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-create-policies-ontap.html["Obtenga más información sobre las políticas"] .



=== Soporte para restaurar archivos y carpetas desde volúmenes en el almacenamiento de objetos ONTAP S3

Anteriormente, no era posible restaurar archivos y carpetas mediante la función “Explorar y restaurar” cuando los volúmenes se respaldaban en el almacenamiento de objetos ONTAP S3.  Esta versión elimina esa restricción.

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html["Obtenga más información sobre la restauración de datos"] .



=== Capacidad de archivar datos de respaldo inmediatamente en lugar de escribirlos primero en el almacenamiento estándar

Ahora puede enviar sus archivos de respaldo inmediatamente al almacenamiento de archivo en lugar de escribir los datos en el almacenamiento en la nube estándar.  Esto puede ser especialmente útil para usuarios que rara vez necesitan acceder a datos de copias de seguridad en la nube o para usuarios que están reemplazando una copia de seguridad en un entorno de cinta.



=== Soporte adicional para realizar copias de seguridad y restaurar volúmenes SnapLock

La copia de seguridad y la recuperación ahora pueden realizar copias de seguridad de los volúmenes FlexVol y FlexGroup que estén configurados mediante los modos de protección SnapLock Compliance o SnapLock Enterprise .  Sus clústeres deben ejecutar ONTAP 9.14 o superior para recibir este soporte.  La realización de copias de seguridad de volúmenes FlexVol mediante el modo SnapLock Enterprise es compatible desde la versión 9.11.1 de ONTAP .  Las versiones anteriores de ONTAP no brindan soporte para realizar copias de seguridad de los volúmenes de protección SnapLock .

https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-ontap-backup-to-cloud.html["Obtenga más información sobre la protección de los datos de ONTAP"] .
