= Compatibilidad con Flash Cache y alta velocidad de escritura en Google Cloud
:allow-uri-read: 


Los siguientes cambios se introdujeron con la versión 3.9.32 del Conector.



=== Compatibilidad con Flash Cache y alta velocidad de escritura en Google Cloud

La caché flash y la alta velocidad de escritura se pueden habilitar por separado en Google Cloud para Cloud Volumes ONTAP 9.13.1 y versiones posteriores. La alta velocidad de escritura está disponible en todos los tipos de instancias compatibles. Flash Cache es compatible con los siguientes tipos de instancias:

* n2-estándar-16
* n2-estándar-32
* n2-estándar-48
* n2-estándar-64


Puede utilizar estas funciones por separado o en conjunto tanto en implementaciones de nodo único como en implementaciones de pares de alta disponibilidad.

link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-deploying-gcp.html["Lanzamiento de Cloud Volumes ONTAP en Google Cloud"^]



=== Mejoras en los informes de uso

Ahora están disponibles varias mejoras en la información mostrada dentro de los informes de uso. Las siguientes son mejoras en los informes de uso:

* La unidad TiB ahora está incluida en el nombre de las columnas.
* Ahora se incluye un nuevo campo "nodo(s)" para números de serie.
* Ahora se incluye una nueva columna “Tipo de carga de trabajo” en el informe de uso de máquinas virtuales de almacenamiento.
* Los nombres de los entornos de trabajo ahora se incluyen en los informes de uso de volúmenes y máquinas virtuales de almacenamiento.
* El tipo de volumen “archivo” ahora está etiquetado como “Principal (lectura/escritura)”.
* El tipo de volumen “secundario” ahora está etiquetado como “Secundario (DP)”.


Para obtener más información sobre los informes de uso, consultelink:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-manage-capacity-licenses.html#download-usage-reports["Descargar informes de uso"^] .
