= Implementaciones pequeñas y medianas temporalmente no disponibles
:allow-uri-read: 




=== Implementaciones pequeñas y medianas temporalmente no disponibles

Cuando implementa una instancia de BlueXP classification en AWS, la opción para seleccionar *Implementar > Configuración* y elegir una instancia de tamaño pequeño o mediano no está disponible en este momento.  Aún puedes implementar la instancia utilizando el tamaño de instancia grande seleccionando *Implementar > Implementar*.



=== Aplique etiquetas en hasta 100.000 elementos desde la página de Resultados de la investigación

En el pasado, solo se podían aplicar etiquetas a una sola página a la vez en la página Resultados de la investigación (20 elementos).  Ahora puede seleccionar *todos* los elementos en las páginas de Resultados de la investigación y aplicar etiquetas a todos los elementos (hasta 100 000 elementos a la vez). https://docs.netapp.com/us-en/bluexp-classification/task-org-private-data.html#assigning-tags-to-files["Vea cómo"] .



=== Identificar archivos duplicados con un tamaño mínimo de archivo de 1 MB

La BlueXP classification se utiliza para identificar archivos duplicados solo cuando los archivos tienen 50 MB o más.  Ahora se pueden identificar archivos duplicados que comiencen con 1 MB.  Puede utilizar los filtros de la página de Investigación "Tamaño de archivo" junto con "Duplicados" para ver qué archivos de un tamaño determinado están duplicados en su entorno.
